### ISSUE TITLE
Petition: Support for Media Features Pack

### ISSUE THREAD

**Issue by Zeioth** [Winetricks/winetricks#1177] opened 2019-02-11 22:47 UTC
Some games like GRIS require [MFP](https://support.microsoft.com/en-us/help/3145500/media-feature-pack-list-for-windows-n-editions). Currently it requires a manual process that could be probably automatized: https://askubuntu.com/a/731192

**Comment by austin987** [comment] 2019-02-11 23:17
Duplicate of #1132

**Closed by austin987** 2019-02-11 23:17 UTC
Labels: duplicate
