### ISSUE TITLE
prefix ignored

### ISSUE THREAD

**Issue by jg00dman** [Winetricks/winetricks#1453] opened 2019-12-23 02:00 UTC
```
env WINEARCH=win32 WINEPREFIX=$HOME/.wine-logos sh winetricks arch=32 prefix=$HOME/
.wine-logos -q dotnet472 corefonts ddr=gdi fontsmooth=rgb win7
```

This set up a prefix at .wine-logos and then went ahead and put dotnet472 into a prefix at .wine

I'd love to have it work and ideally automatically not install mono or gecko without having to click cancel.

Help much appreciated.

**Comment by austin987** [comment] 2019-12-23 05:27
You don't need to specify both WINEARCH/arch= or WINEPREFIX/prefix=, they both accomplish the same thing.

This should be fixed in git (I plan to make a new release soon), your command works for me here.

For mono/gecko, you either need to install the packaged versions if available on your distro, or let wine cache them. Winetricks doesn't have any control over that.

**Comment by jg00dman** [comment] 2019-12-23 16:06
`winetricks arch=32 prefix=$HOME/.wine-logos -q dotnet472 corefonts ddr=gdi fontsmooth=rgb win7`
n.b. I don't want mono or gecko the app I'm running works with dotnet472 and chromekit.
So this should work as is? Many thanks!

**Comment by austin987** [comment] 2019-12-29 14:40
Please retest in winetricks-20191224

**Comment by zgldh** [comment] 2020-02-06 15:44
Still ignored.

**Command**
```
winetricks prefix=office2013pro office2013pro
```

**Output**
```
[zgldh@zgldh-manjaro Projects]$ winetricks prefix=office2013pro office2013pro
Using winetricks 20191224 - sha256sum: afe039a7d72553cb761f0367f9f2085b92af8caf86e025c34bbc1fdd89a1f9ee with wine-5.0 and WINEARCH=win32
Executing w_do_call office2013pro
Executing load_office2013pro 
操作完成
Setting Windows version to win7
Executing wine regedit C:\windows\Temp\set-winver.reg
------------------------------------------------------
*Running /usr/bin/wineserver -w. This will hang until all wine processes in prefix=/home/zgldh/.wine terminate*
------------------------------------------------------
Executing w_do_call corefonts
corefonts already installed, skipping
Executing w_do_call tahoma
tahoma already installed, skipping
Executing w_do_call riched20
riched20 already installed, skipping
```

**Version**
```
[zgldh@zgldh-manjaro Projects]$ winetricks -V
20191224 - sha256sum: afe039a7d72553cb761f0367f9f2085b92af8caf86e025c34bbc1fdd89a1f9ee
```

**Comment by austin987** [comment] 2020-02-08 07:25
Thanks for the clear instructions to reproduce.

https://github.com/austin987/winetricks/commit/a84a3cec2279466d0ca3c4ed9be5d967b0fbbd69 should help (note: not committed yet, it's on a branch). I want to add tests before committing, and see if there's a cleaner way to fix it. Testing would be appreciated, though.

**Comment by austin987** [comment] 2020-03-21 04:03
https://github.com/Winetricks/winetricks/commit/f9e18add7da8d1feee1ac6524944aeefce131acc

**Closed by austin987** 2020-03-21 04:03 UTC
