### ISSUE TITLE
mspatcha install fails "no valid cabinets found"

### ISSUE THREAD

**Issue by jfk75** [Winetricks/winetricks#1120] opened 2018-10-31 07:42 UTC
Hi,
I wanted to install Adobe Reader DC, and somewhere on the net I read that I need to install mspatcha first. I tried so with winetricks (actual version, fresh download as of today). "winetricks mspatcha" leads to apparently downloading the file, but it ends up with an error message: 
"Note: command cabextract -q --directory= (...)_mspatcha/i386/mspatcha.dl_ returned status 1. Aborting."
And before it says: 
".wine/dosdevices/c:/windows/temp/_mspatcha/i386/mspatcha.dl_: no valid cabinets found"
I didn't find anything related with a quick search. Can anybody help me?
Kind regards,
John

**Comment by qwertychouskie** [comment] 2018-11-01 02:17
Looks like a problem with the underscores?  Maybe the FS being used is buggy.  Is it just EXT4 or something else?

**Comment by Goatroth** [comment] 2018-11-01 03:38
I have the same issue, it seems to affect anything where cabextract is involved. Here is the full output of the above command:

    goatroth@nephilim:~$ winetricks mspatcha
    ------------------------------------------------------
    You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
    ------------------------------------------------------
    Using winetricks 20180815 - sha256sum: 29e664ec1e879271a33167bf367deaa188cbe803d44b540e692bd669c44a2804 with wine-3.19 and WINEARCH=win64
    Executing w_do_call mspatcha
    Executing load_mspatcha 
    Executing mkdir -p /home/goatroth/.cache/winetricks/win2ksp4
    Executing cd /home/goatroth/.cache/winetricks/win2ksp4
    Downloading https://ftp.gnome.org/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Service_Packs/usa/W2KSP4_EN.EXE to /home/goatroth/.cache/winetricks/win2ksp4
    --2018-10-31 23:32:00--  https://ftp.gnome.org/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Service_Packs/usa/W2KSP4_EN.EXE
    Resolving ftp.gnome.org (ftp.gnome.org)... 194.71.11.173, 194.71.11.165, 2001:6b0:19::165, ...
    Connecting to ftp.gnome.org (ftp.gnome.org)|194.71.11.173|:443... connected.
    HTTP request sent, awaiting response... 302 Found
    Location: https://saimei.ftp.acc.umu.se/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Service_Packs/usa/W2KSP4_EN.EXE [following]
    --2018-10-31 23:32:01--  https://saimei.ftp.acc.umu.se/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Service_Packs/usa/W2KSP4_EN.EXE
    Resolving saimei.ftp.acc.umu.se (saimei.ftp.acc.umu.se)... 194.71.11.138, 2001:6b0:19::138
    Connecting to saimei.ftp.acc.umu.se (saimei.ftp.acc.umu.se)|194.71.11.138|:443... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: 135477136 (129M) [application/x-msdownload]
    Saving to: ‘W2KSP4_EN.EXE’
    
    W2KSP4_EN.EXE             100%[====================================>] 129.20M  6.20MB/s    in 22s     
    
    2018-10-31 23:32:24 (5.80 MB/s) - ‘W2KSP4_EN.EXE’ saved [135477136/135477136]
    
    Executing cd /home/goatroth
    Executing cabextract -q -d /home/goatroth/.wine/dosdevices/c:/windows/temp/_mspatcha -L -F i386/mspatcha.dl_ /home/goatroth/.cache/winetricks/win2ksp4/W2KSP4_EN.EXE
    Executing cabextract -q --directory=/home/goatroth/.wine/dosdevices/c:/windows/syswow64 /home/goatroth/.wine/dosdevices/c:/windows/temp/_mspatcha/i386/mspatcha.dl_
    /home/goatroth/.wine/dosdevices/c:/windows/temp/_mspatcha/i386/mspatcha.dl_: no valid cabinets found
    ------------------------------------------------------
    Note: command cabextract -q --directory=/home/goatroth/.wine/dosdevices/c:/windows/syswow64 /home/goatroth/.wine/dosdevices/c:/windows/temp/_mspatcha/i386/mspatcha.dl_ returned status 1. Aborting.
    ------------------------------------------------------

As stated above, it affects anything where cabextract is involved. i'm not entirely sure it's a WINE/winetricks problem as I have tried manually extracting various MS EXEs with cabextract and it's always produced corrupt cabs (but only when using -F). This is a recent issue as well, as I was able to use winetricks without issue only a week ago.

**Comment by austin987** [comment] 2018-11-01 03:46
Sounds like a  cabextract regression. What version are you using?

**Comment by Goatroth** [comment] 2018-11-01 03:52
1.6-1.1 - the latest version on Debian testing/unstable.

**Comment by austin987** [comment] 2018-11-01 17:04
For me on Gentoo, it works with 1.6 and 1.7, fails with 1.8.

Looks like upstream bug; I'll try to bisect if I have time.

**Comment by austin987** [comment] 2018-11-02 17:56
Fixed upstream in cabextract. Thanks for the detailed report @Goatroth. You'll likely want to forward this to Debian so they can backport the patch.

**Closed by austin987** 2018-11-02 17:56 UTC

**Comment by jre-wine** [comment] 2019-06-12 17:21
Debian Buster now finally has the good libmspack 0.10.1-1, instead of the broken 0.8-1. So in all Debian releases "cabextract -F" should now work again.

Ubuntu had a better timing, and was only affected for a short while last year.

With other words: The cause for this issue and https://github.com/Winetricks/winetricks/issues/1154, https://github.com/Winetricks/winetricks/issues/1172, https://github.com/Winetricks/winetricks/issues/1178, https://github.com/Winetricks/winetricks/issues/1193, and eventually others is fixed.

If you put any warnings about this issue anywhere, you can remove them now.
