### ISSUE TITLE
Adult Content Filter doesn't like web.archive.org URLs during file download

### ISSUE THREAD

**Issue by andwan0** [Winetricks/winetricks#2290] opened 2024-11-03 01:20 UTC
During vc2019 downloading via install components....

Downloading **https://web.archive.org/web/2000/https://web.archive.org/web/20210415064013/https://download.visualstudio.microsoft.com/download/pr/85d47aa9-69ae-4162-8300-e6b7e4bf3cf3/14563755AC24A874241935EF2C22C5FCE973ACB001F99E524145113B2DC638C1/VC_redist.x86.exe** failed

But if I manually copy this into my web browser and remove the duplicate starting part of the URL then it works.

**Comment by JonnyTech** [comment] 2024-11-03 10:04
The problem is not with winetricks. Please raise the issue with your content filter provider. They are categorising incorrectly. Please close.

**Comment by Chiitoo** [comment] 2024-11-07 09:01
Going by the edited content, it may have been an intermittent problem (right now the archive takes too long to respond to my request for that URL as well).

If you have an issue with Winetricks, please attach the log file for the erroneous run, making sure you are using an up-to-date version of Winetricks (if your operating system does not provide the latest release via the package manager for example, you can simply download the script from this repository and run it directly, and even if it did provide the latest release, it might already be fixed in "git master").

Thank you!

**Closed by Chiitoo** 2024-11-07 09:01 UTC

**Comment by andwan0** [comment] 2024-11-08 16:01
I can access web.archive.org URL fine.
But if you look carefully, it looks like there's too many appending on the URL. It's like trying a web.archive.org on a web.archive.org URL itself.

**Comment by Chiitoo** [comment] 2024-11-08 18:53
Yeah, I believe the appending business is normal, but there might have been some change at archive.org as I did see something weird with it before.  Thought I already created an issue for investigating it...

In any case, assuming the verb here is `vcrun2019`, testing it (`winetricks -q vcrun2019`) works for me via Winetricks right now, with the URL being redirected correctly (tested with both 'aria2' and 'wget' as the downloader).

If you can share the log of a failed run, that should help in confirming what is going wrong there.
