### ISSUE TITLE
Workaround for Wine bug 30713 is still being applied, even though the bug was fixed in 3.8.

### ISSUE THREAD

**Issue by Valmar33** [Winetricks/winetricks#1631] opened 2020-10-10 11:12 UTC
Was fixed by https://source.winehq.org/git/wine.git/commitdiff/540c48b91175b11c7b8646d0a036b20c46425080

https://bugs.winehq.org/show_bug.cgi?id=30713#c22

Yet, the workaround was always applied for me.

Removing the workaround lines, vcrun installs properly.

**Comment by gverm** [comment] 2020-10-10 11:22
Yeah I can confirm, I mentioned it in https://github.com/Winetricks/winetricks/issues/1560#issuecomment-702104466 as well. It seems to be a general problem with w_workaround_wine().

**Comment by austin987** [comment] 2020-10-11 09:01
Thanks for opening the bug; I saw @gverm's comment and had a note to check, but hadn't yet :/.

Anyway, when I fixed up w_compare_version(), I ran `make check` for several wine versions (i.e., 4.0/5.0/5.x), but I didn't audit the rest (meant to, but didn't).

In the case of dotnet40/vcrun2008, they were backwards. However, given that it's fixed in 3.x, I don't think it's worth keeping around, so I've removed it instead:
https://github.com/austin987/winetricks/tree/remove-workarounds

I want to audit the other bugs (and run more tests) before pushing.

**Comment by MadByteDE** [comment] 2020-10-19 08:42
Hey. May I ask if winetricks version `61509663b824d72daafec6a95986e5b256e19e0e8ec1d2b7c4e89cf52665d63b` is the newst version without the workaround for bug 30713? Because if so, there is a problem while installing vcrun2017 for a game called "Foundation". The installation of vcrun2017 worked with version `8efa7c2d4b96045bf6dec3a4b60be588c4c9a7da4e6de7c010cb6f21e2fb708f`, but doesn't work anymore. The only difference in the log seems to be the following part:
```
------------------------------------------------------
warning: Wine-Fehler 30713 wird umgegangen -- Manually extracting the 64-bit dlls
------------------------------------------------------
Executing cabextract -q --directory=/home/larsl/.steam/steam/steamapps/compatdata/690830/pfx/dosdevices/c:/windows/temp vc_redist.x64.exe
Executing cabextract -q --directory=/home/larsl/.steam/steam/steamapps/compatdata/690830/pfx/dosdevices/c:/windows/temp /home/larsl/.steam/steam/steamapps/compatdata/690830/pfx/dosdevices/c:/windows/temp/a10
/home/larsl/.steam/steam/steamapps/compatdata/690830/pfx/dosdevices/c:/windows/temp/a10: WARNING; possible 16776 extra bytes at end of file.
Executing cabextract -q --directory=/home/larsl/.steam/steam/steamapps/compatdata/690830/pfx/dosdevices/c:/windows/temp /home/larsl/.steam/steam/steamapps/compatdata/690830/pfx/dosdevices/c:/windows/temp/a11
/home/larsl/.steam/steam/steamapps/compatdata/690830/pfx/dosdevices/c:/windows/temp/a11: WARNING; possible 16976 extra bytes at end of file.
```
Previous versions (before `8efa7c2d4b96045bf6dec3a4b60be588c4c9a7da4e6de7c010cb6f21e2fb708f)` also were missing this part in the log and the game didn't run after installing vcrun2017.

More about the issue with the game can be read here:
https://github.com/ValveSoftware/Proton/issues/2318#

Could you double check the commit please?

**Comment by gverm** [comment] 2020-10-19 08:49
@MadByteDE You are definitely not running winetricks-git. The code you are hitting was removed in https://github.com/Winetricks/winetricks/commit/279bd357cf5baa780807acc436624c22218e3131

@austin987 There is still an easy left with vcrun2017 (and probably others). It's not really a problem, but a little confusing. I see this in the log: `warning: Working around wine bug 37781 -- ,4.15`

**Comment by MadByteDE** [comment] 2020-10-19 09:21
@gverm My version is up-to-date ( `61509663b824d72daafec6a95986e5b256e19e0e8ec1d2b7c4e89cf52665d63b` ).
The issue is, without this workaround the game won't work. I just applied the removed workaround code you referred to to the latest winetricks version and the game works again.

**Comment by gverm** [comment] 2020-10-19 09:26
@MadByteDE That is probably not a winetricks bug, but a wine bug. I think I remember someone reporting before that ucrtbase.dll doesn't get replaced when the installer is used. This is something that can be worked around in winetricks, but should be investigated first and deserves its own issue.

**Comment by gverm** [comment] 2020-12-17 00:09
@Valmar33 This should be working with the latest release of winetricks. Please retest and close this issue if it works now.

**Closed** 2022-04-11 20:49 UTC
Labels: bug, download
