### ISSUE TITLE
Error when installing dotnet30sp1

### ISSUE THREAD

**Issue by p4ntek** [Winetricks/winetricks#519] opened 2015-07-10 17:23 UTC
"Wrong variable"
Solution:
Change
"XPSEP XP and Server 2003 32 bit.msi"
to:
"XPSEPXPandServer200332bit.msi"

in line with "w_download" and in line with "w_try "$WINE" msiexec /i"

**Comment by austin987** [comment] 2015-07-10 23:31
I'm not able to reproduce this, downloading the file here works, and is definitely named "XPSEP XP and Server 2003 32 bit.msi", with spaces in the filename.

**Comment by p4ntek** [comment] 2015-07-10 23:59
"winetricks --force dotnet30sp1
Executing w_do_call dotnet30sp1
Executing load_dotnet30sp1
/usr/bin/winetricks: 504: local: 2003: bad variable name
"
WINETRICKS_VERSION=20150706
1.6.2
Done on "PlayOnLinux"

**Comment by austin987** [comment] 2015-07-11 02:15
I suspect this may be related to issue 517, could you try latest git?

**Comment by p4ntek** [comment] 2015-07-11 17:31
Exactly. This part of code makes error. 
Changed to new winetricks to prevent further error with spaces in files :)

**Comment by austin987** [comment] 2015-07-11 22:34
Cool, closing.

**Closed by austin987** 2015-07-11 22:34 UTC
