### ISSUE TITLE
Digital Editions new version?

### ISSUE THREAD

**Issue by Thomas-O** [Winetricks/winetricks#561] opened 2015-10-19 18:56 UTC
Please can you add support for a more recent version of Adobe's Digital Editions?

I have happily used version 1.7.2 for many years but in the last few months I have noticed that it no longer works with an increasing number of e-book stores. A while back I read something about Adobe's implementation of a new DRM scheme to be included in versions 3.0+. This new scheme will demand that the end-user continually upgrades their copy of Digital Editions to the latest version. I don't know if the failures are as a result of stores upgrading their back-end software to match Adobe's newer versions. But it might be. And my fear is that without a working version of Digital Editions 4.0 or 4.5 then in a year or two from now it might again be impossible to download a DRM e-book to a Linux desktop.

Thanks for your time.

Thomas

**Comment by austin987** [comment] 2015-10-29 01:58
I'll take a look at some point, but would appreciate if someone else uploaded a patch for review.

**Comment by austin987** [comment] 2015-11-04 01:15
Fixed by https://github.com/Winetricks/winetricks/commit/b395dd86988303060dff518809ced08ffddb01aa

**Closed by austin987** 2015-11-04 01:15 UTC

**Comment by eli-schwartz** [comment] 2015-11-04 21:26
???

I thought the reason this was stuck at version 1.7 is because the newer versions don't work!
Did you check it? Have you gotten it to work? If so, I'd love to know your secret...

Because sure enough, I tried installing adobe_diged into a fresh wineprefix, and Adobe Digital Editions instantly crashes.

ArchLinux latest
wine 1.7.54-1
winetricks-git 20150826.r27.gb395dd8-1


Please revert this. Better to have a version of ADE which doesn't support the new super-fancy DRM :wink: than a version of ADE which doesn't work at all.

**Comment by eli-schwartz** [comment] 2015-11-04 21:34
As for the DRM...

Adobe supports the new DRM system introduced in ADE 3.0 as well as the old system.
Bookstores have to specifically enable the new DRM. Many haven't, if only because there are no E-Ink ereaders out there that run a new enough version of RMSDK to support the new DRM, and people will start getting angry if they can't use their ereaders to read their books...

AFAIK the popular bookstores (at least in the US) still use the old system, so ADE 1.7 still works fine.
Kobo, Google Play, etc.
(B&N of course stopped allowing you to download their books with ADE at all.)


I was under the impression that it was a very rare bookstore which would enforce the new DRM.

**Comment by austin987** [comment] 2015-11-04 21:37
This launched for me without crashing. I didn't try loading any books.

What crash are you seeing / how to reproduce?

**Comment by eli-schwartz** [comment] 2015-11-04 22:21
Well, I take it all back.
Once I install samba and retry running DigitalEditions.exe, it works fine.

But until then it was simply crashing on startup, it's that simple...
Is there any way to warn people during the install that it will fail miserably unless samba is installed?

**Comment by austin987** [comment] 2015-11-04 22:28
I don't we should have to, but there are similar warnings in other
places..Anyway, please open a new issue for that.

On Wed, Nov 4, 2015 at 4:21 PM, Eli Schwartz <notifications@github.com>
wrote:

> Well, I take it all back.
> Once I install samba and retry running DigitalEditions.exe, it works fine.
>
> But until then it was simply crashing on startup, it's that simple...
> Is there any way to warn people during the install that it will fail
> miserably unless samba is installed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Winetricks/winetricks/issues/561#issuecomment-153887821>
> .
>



-- 
-Austin

**Comment by eli-schwartz** [comment] 2015-11-05 00:06
I can do that...


But regarding the update, I am still not entirely thrilled.
I can think of two reasons why someone might specifically want the older version.
* As I understand it, there is an Adobe Content Server option to let people use the old DRM, if they download for the first time using a method that does NOT support the new Adobe DRM. But if they download with ADE 3+, it will deliver the new DRM, and lock you into it. If your E-Ink device doesn't support the new DRM, you can get trapped **because** you had an updated ADE.
* Some people would boycott the stores that enforce new DRM. It is easy to know if the new DRM is used, since it won't download in ADE1.7; I also, um, "heard" that the Apprentices of Alf don't work well with the new DRM, which is something they want to know immediately. :wink:

I can hear wanting ADE4.5, and I can hear wanting ADE1.7, although I understand this is verging on making a political statement...


Does Winetricks have any strong feelings about offering two different versions of the same app?

**Comment by austin987** [comment] 2015-11-05 22:59
In general we avoid it, unless there's a convincing reason for actually needing both (or more) versions, i.e., .Net.

I'd be okay with multiple versions, but I don't know what they should be named. I.e., should adobe_diged be used for 1.7 and adboe_diged_45 for the new version?
