### ISSUE TITLE
Error when installing windowscodecs

### ISSUE THREAD

**Issue by laichiaheng** [Winetricks/winetricks#969] opened 2018-04-17 04:53 UTC
![deepin _20180417125237](https://user-images.githubusercontent.com/9532105/38849402-588788c8-423e-11e8-8e76-c8dc54964f5f.png)
![deepin _20180417125243](https://user-images.githubusercontent.com/9532105/38849403-58b0b748-423e-11e8-8672-2fcdff312faa.png)
![deepin _20180417125248](https://user-images.githubusercontent.com/9532105/38849404-58e2ea7e-423e-11e8-91f7-89171e0feeac.png)
```
Using winetricks 20180217-next - sha256sum: 301273d68c60cc07e003110a15b7ca370c48e8739c18de3ada98168b2a16076a with wine-3.6 (Staging) and WINEARCH=win32
Gtk-Message: 12:52:05.743: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: 12:52:09.256: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: 12:52:16.754: GtkDialog mapped without a transient parent. This is discouraged.
Executing w_do_call windowscodecs
Executing load_windowscodecs 
Executing rm -f /home/laichiaheng/.wine32/dosdevices/c:/windows/system32/windowscodecs.dll /home/laichiaheng/.wine32/dosdevices/c:/windows/system32/windowscodecsext.dll /home/laichiaheng/.wine32/dosdevices/c:/windows/system32/photometadatahandler.dll
Using native override for following DLLs: windowscodecs windowscodecsext
Executing wine regedit C:\windows\Temp\_windowscodecs\override-dll.reg
000b:fixme:winediag:start_process Wine Staging 3.6 is a testing version containing experimental patches.
000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
Setting Windows version to winxp
Executing wine regedit C:\windows\Temp\_windowscodecs\set-winver.reg
------------------------------------------------------
Running /usr/bin/wineserver -w. This will hang until all wine processes in prefix=/home/laichiaheng/.wine32 terminate
------------------------------------------------------
Gtk-Message: 12:52:22.963: GtkDialog mapped without a transient parent. This is discouraged.
Executing cd /home/laichiaheng/.cache/winetricks/windowscodecs
------------------------------------------------------
繞過 wine bug 32859 -- Working around possibly broken libX11
------------------------------------------------------
Gtk-Message: 12:52:41.058: GtkDialog mapped without a transient parent. This is discouraged.
Executing taskset -c 0 wine wic_x86_enu.exe /passive
000b:fixme:winediag:start_process Wine Staging 3.6 is a testing version containing experimental patches.
000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
000d:err:module:import_dll Library windowscodecs.dll (which is needed by L"C:\\windows\\system32\\winemenubuilder.exe") not found
000d:err:module:attach_dlls Importing dlls for L"C:\\windows\\system32\\winemenubuilder.exe" failed, status c0000135
0009:fixme:clusapi:GetNodeClusterState ((null),0x32ec44) stub!
0009:fixme:advapi:DecryptFileA ("y:\\711286d6862ce4c7ea67\\", 00000000): stub
0030:fixme:setupapi:pSetupGetGlobalFlags stub
------------------------------------------------------
Note: command taskset -c 0 wine wic_x86_enu.exe /passive returned status 67. Aborting.
------------------------------------------------------
Gtk-Message: 12:52:46.057: GtkDialog mapped without a transient parent. This is discouraged.
```

**Comment by austin987** [comment] 2018-04-20 21:47
This is a duplicate of #955, which was fixed by https://github.com/Winetricks/winetricks/commit/f4d7b0ac35ae6bd1e23f2d904b31c9739ce3fc88

**Closed by austin987** 2018-04-20 21:47 UTC
