### ISSUE TITLE
Web archive is down

### ISSUE THREAD

**Issue by tinkicker** [Winetricks/winetricks#2136] opened 2023-10-10 23:25 UTC
Hi, I've seen a few issues here, including one just two days ago about broken links on web archive. I'm here because in setting up an application in Winetricks on Linux Mint I've run into dead links for corefonts and .net installs, which aren't really dead...the server is down. I see that apparently winetricks draws all of these sorts of packages from the web archive, but in reading comments on isitdownrightnow.com I see that (including right now) the site is down quite a bit and for indeterminate lengths of time (like now...hour and a half so far).

I'm sure it's been asked ad nauseum, but are there any other server systems from where Winetricks, Inc. could store/draw the various packages? Maybe two or three storage solutions to guard against this sort of thing. How about Mega? Fortunately I've got another production machine I'd already setup, but judging by the many server down situations documented, I'm dead in the water on this setup until somebody turns the lights back on at Wayback Machine Central.

Thanks for reading.

**Comment by BrandowLucas** [comment] 2023-10-11 04:04
Vouch that, i have been trying to install arial font through winetricks, but couldn't because i get the error:

warning: Downloading https://web.archive.org/web/2000/https://mirrors.kernel.org/gentoo/distfiles/5e/arial32.exe failed

Even though the link is clearly working.

**Comment by Chiitoo** [comment] 2023-10-11 09:37
Usually the archive is the secondary option, and which is the case with these fonts for example.

That said, a handful of years ago, Gentoo Linux changed the distfile layout [1], and recently compatibility links to the old were removed.

While the URLs are fixed in 'git master' of Winetricks, some mirrors were still carrying files that should have been removed already a while ago, until quite recently from the looks of it, so for example in the case of 'arial32.exe', the archive is the only option right now.

The archive is working for me right now at least, so perhaps it's a problem on the route instead (or very intermittent).

1. https://www.gentoo.org/glep/glep-0075.html

**Comment by tinkicker** [comment] 2023-10-11 11:02
The archive came back up for me exactly two hours after it went down, so I suspect most likely it was server maintenance. I was able to get to the main web archive page all through that time though, and there was nothing posted there about any downtime of any sort whatsoever. 😒

**Comment by strycore** [comment] 2023-10-11 19:50
Gentoo doesn't ship arial32.exe anymore. They haven't referenced the file here: https://github.com/gentoo/gentoo/blob/master/media-fonts/corefonts/Manifest

You can replace the Gentoo link with https://github.com/pushcx/corefonts/raw/master/arial32.exe

Also, downloading archive.org URLs can cause problems when wget2 is used, see: https://github.com/Winetricks/winetricks/pull/2130

**Comment by strycore** [comment] 2023-10-11 19:51
Lutris now ships a patched version with the Gentoo URL replaced with the Github URL for arial32.exe

**Comment by strycore** [comment] 2023-10-11 19:56
Hosting the files on Internet Archive (not The Wayback Machine) would be a good idea.

**Comment by omerav** [comment] 2023-10-12 11:26
I got the same error for trying to install VC_redist.x86.exe
 warning: Downloading https://web.archive.org/web/2000/https://web.archive.org/web/20210415064013/https://download.visualstudio.microsoft.com/download/pr/85d47aa9-69ae-4162-8300-e6b7e4bf3cf3/14563755AC24A874241935EF2C22C5FCE973ACB001F99E524145113B2DC638C1/VC_redist.x86.exe failed

**Comment by CrookedBIOS** [comment] 2023-10-14 10:55
> I got the same error for trying to install VC_redist.x86.exe 

I also experienced this error when trying to install RDR2 and the Rockstar Games Launcher. I've found a workaround by editing the winetricks script directly, which in my case is located at `/home/$USER/.local/share/lutris/runtime/winetricks/winetricks`, and reverting back to the URLs directly from Microsoft instead of web.archive. Seems like download directly from Microsoft is working (again).

In winetricks script starting from line 13427

```
load_ucrtbase2019()
{
    w_override_dlls native,builtin ucrtbase

    # Microsoft download no longer containts ucrtbase so get the last known version from archive.org
    #w_download https://web.archive.org/web/20210415064013/https://download.visualstudio.microsoft.com/download/pr/85d47aa9-69ae-4162-8300-e6b7e4bf3cf3/14563755AC24A874241935EF2C22C5FCE973ACB001F99E524145113B2DC638C1/VC_redist.x86.exe 14563755ac24a874241935ef2c22c5fce973acb001f99e524145113b2dc638c1

    w_download https://download.visualstudio.microsoft.com/download/pr/85d47aa9-69ae-4162-8300-e6b7e4bf3cf3/14563755AC24A874241935EF2C22C5FCE973ACB001F99E524145113B2DC638C1/VC_redist.x86.exe 14563755ac24a874241935ef2c22c5fce973acb001f99e524145113b2dc638c1

    w_try_cabextract --directory="${W_TMP}/win32"  "${W_CACHE}"/"${W_PACKAGE}"/VC_redist.x86.exe -F 'a10'
    w_try_cabextract --directory="${W_SYSTEM32_DLLS}" "${W_TMP}/win32/a10" -F 'ucrtbase.dll'

    case "${W_ARCH}" in
        win64)
            # Microsoft download no longer containts ucrtbase so get the last known version from archive.org
            #w_download https://web.archive.org/web/20210414165612/https://download.visualstudio.microsoft.com/download/pr/85d47aa9-69ae-4162-8300-e6b7e4bf3cf3/52B196BBE9016488C735E7B41805B651261FFA5D7AA86EB6A1D0095BE83687B2/VC_redist.x64.exe 52b196bbe9016488c735e7b41805b651261ffa5d7aa86eb6a1d0095be83687b2

            w_download https://download.visualstudio.microsoft.com/download/pr/85d47aa9-69ae-4162-8300-e6b7e4bf3cf3/52B196BBE9016488C735E7B41805B651261FFA5D7AA86EB6A1D0095BE83687B2/VC_redist.x64.exe 52b196bbe9016488c735e7b41805b651261ffa5d7aa86eb6a1d0095be83687b2

            w_try_cabextract --directory="${W_TMP}/win64"  "${W_CACHE}"/"${W_PACKAGE}"/VC_redist.x64.exe -F 'a10'
            w_try_cabextract --directory="${W_SYSTEM64_DLLS}" "${W_TMP}/win64/a10" -F 'ucrtbase.dll'
            ;;
    esac
}
```

The sha256 hash is still the same when downloading directly from Microsoft.

**Comment by mactan-sc** [comment] 2023-10-14 19:15
We are also experiencing this issue for Arial and vcrun2019 when attempting to install the launcher for the video game Star Citizen using Lutris. As a workaround, users have been able to download the files manually to their respective winetricks cache directories before re-trying, or  they create a separate dummy prefix with a generous timeout value to prime the cache.

for example:

`WINEPREFIX="$HOME/.wine-sc-preload" WINETRICKS_DOWNLOADER_TIMEOUT=60 winetricks --force arial vcrun2019 win10`

**Comment by Chiitoo** [comment] 2023-10-14 20:02
Logs of the run would be nice to see from people affected.

I'm wondering if some people are just hitting the un-updated URLs issue rather than the archive being down.

Also, indeed. kind of usual for the archive to be so down.

**Comment by kenorb** [comment] 2023-10-16 12:06
When a [.verb file](https://github.com/EA31337/ansible-role-metatrader/blob/9cbf10456a22aa343acb4f1fe685cbcd70a8c2f4/templates/mt5_install.verb.j2) has the following section, it fails to access some endpoints (with 404) when calling `opensymbol`:

    if w_workaround_wine_bug 7156 "${title} needs wingdings.ttf, installing opensymbol"
    then
        w_call opensymbol
    fi

as per https://github.com/Winetricks/winetricks/issues/1357#issuecomment-1763371984

**Comment by AndnixSH** [comment] 2023-10-17 16:12
Not sure if this is related but here is the logs when I try to install Arial font

```
od: wine: No such file or directory
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20230212-next - sha256sum: fe0550e0d843214f87dcb0f4aa591be0046fa93db7b8330217dd926258e628fc with wine-8.18 and WINEARCH=win64
winetricks GUI enabled, using zenity 3.32.0
Executing w_do_call arial
od: wine: No such file or directory
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_arial 
Executing cd /home/codespace/.cache/winetricks/corefonts
Downloading https://mirrors.kernel.org/gentoo/distfiles/5e/arial32.exe to /home/codespace/.cache/winetricks/corefonts
Executing cd /home/codespace
------------------------------------------------------
SHA256 mismatch!

URL: https://mirrors.kernel.org/gentoo/distfiles/5e/arial32.exe
Downloaded: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Expected: 85297a4d146e9c87ac6f74822734bdee5f4b2a722d7eaa584b7f2cbf76f478f6

This is often the result of an updated package such as vcrun2019.
If you are willing to accept the risk, you can bypass this check.
Alternatively, you may use the --force option to ignore this check entirely.

Continue anyway?
------------------------------------------------------
Executing cabextract -q -d /home/codespace/.wine/dosdevices/c:/windows/temp /home/codespace/.cache/winetricks/corefonts/arial32.exe
/home/codespace/.cache/winetricks/corefonts/arial32.exe: no valid cabinets found
------------------------------------------------------
warning: Note: command cabextract -q -d /home/codespace/.wine/dosdevices/c:/windows/temp /home/codespace/.cache/winetricks/corefonts/arial32.exe returned status 1. Aborting.
------------------------------------------------------

```

**Comment by Chiitoo** [comment] 2023-10-17 16:35
> Not sure if this is related but here is the logs when I try to install Arial font

Yes, the file 'arial32.exe' no longer exists on that mirror.

Not sure why it is not trying the archive instead for you (or if it is just not shown there).

You could download the file manually from the archive [1] if/when it works for you, and place it under the directory you see in the logs:

` /home/codespace/.cache/winetricks/corefonts `

1. https://web.archive.org/web/2000/https://mirrors.kernel.org/gentoo/distfiles/arial32.exe

**Comment by mrdev023** [comment] 2023-10-22 18:24
Executing cd ~/.var/app/net.lutris.Lutris/cache/winetricks/vcrun2019
------------------------------------------------------
SHA256 mismatch!

URL: https://web.archive.org/web/20210415064013/https://download.visualstudio.microsoft.com/download/pr/85d47aa9-69ae-4162-8300-e6b7e4bf3cf3/14563755AC24A874241935EF2C22C5FCE973ACB001F99E524145113B2DC638C1/VC_redist.x86.exe
Downloaded: d443e697bf89a2979eb5933094f8f94fd9e360548347c847c7a05c4f688ec7e4
Expected: 14563755ac24a874241935ef2c22c5fce973acb001f99e524145113b2dc638c1

**Comment by chengstark** [comment] 2023-10-24 16:53
------------------------------------------------------
Executing cd /home/deck/.var/app/net.lutris.Lutris/cache/winetricks/vcrun2019
Executing /home/deck/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-GE-Proton8-17-x86_64/bin/wine vc_redist.x86.exe /q
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
Using native,builtin override for following DLLs: vcruntime140_1
Executing /home/deck/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-GE-Proton8-17-x86_64/bin/wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\override-dll.reg
Executing /home/deck/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-GE-Proton8-17-x86_64/bin/wine64 C:\windows\regedit.exe /S C:\windows\Temp\override-dll.reg
grep: warning: stray \ before /
Executing /home/deck/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-GE-Proton8-17-x86_64/bin/wine vc_redist.x64.exe /q
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
Executing w_do_call ucrtbase2019
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_ucrtbase2019 
Using native,builtin override for following DLLs: ucrtbase
Executing /home/deck/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-GE-Proton8-17-x86_64/bin/wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\override-dll.reg
Executing /home/deck/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-GE-Proton8-17-x86_64/bin/wine64 C:\windows\regedit.exe /S C:\windows\Temp\override-dll.reg
grep: warning: stray \ before /
------------------------------------------------------
warning: Checksum for /home/deck/.var/app/net.lutris.Lutris/cache/winetricks/ucrtbase2019/VC_redist.x86.exe did not match, retrying download
------------------------------------------------------
Executing cd /home/deck/.var/app/net.lutris.Lutris/cache/winetricks/ucrtbase2019
Downloading https://web.archive.org/web/20210415064013/https://download.visualstudio.microsoft.com/download/pr/85d47aa9-69ae-4162-8300-e6b7e4bf3cf3/14563755AC24A874241935EF2C22C5FCE973ACB001F99E524145113B2DC638C1/VC_redist.x86.exe to /home/deck/.var/app/net.lutris.Lutris/cache/winetricks/ucrtbase2019
[0] Downloading 'https://web.archive.org/web/20210415064013/https://download.visualstudio.microsoft.com/download/pr/85d47aa9-69ae-4162-8300-e6b7e4bf3cf3/14563755AC24A874241935EF2C22C5FCE973ACB001F99E524145113B2DC638C1/VC_redist.x86.exe' ...
Saving 'VC_redist.x86.exe'
HTTP response 200  [https://web.archive.org/web/20210415064013/https://download.visualstudio.microsoft.com/download/pr/85d47aa9-69ae-4162-8300-e6b7e4bf3cf3/14563755AC24A874241935EF2C22C5FCE973ACB001F99E524145113B2DC638C1/VC_redist.x86.exe]
Executing cd /home/deck/.var/app/net.lutris.Lutris/cache/winetricks/vcrun2019
------------------------------------------------------
SHA256 mismatch!

URL: https://web.archive.org/web/20210415064013/https://download.visualstudio.microsoft.com/download/pr/85d47aa9-69ae-4162-8300-e6b7e4bf3cf3/14563755AC24A874241935EF2C22C5FCE973ACB001F99E524145113B2DC638C1/VC_redist.x86.exe
Downloaded: f1d92db72415bff48e5b3ee0f67bb79039c839ca009056318d8c2129da7947e7
Expected: 14563755ac24a874241935ef2c22c5fce973acb001f99e524145113b2dc638c1

This is often the result of an updated package such as vcrun2019.
If you are willing to accept the risk, you can bypass this check.
Alternatively, you may use the --force option to ignore this check entirely.

Continue anyway?
------------------------------------------------------
------------------------------------------------------
Unattended mode, not prompting for confirmation
------------------------------------------------------
Executing cabextract -q --directory=/home/deck/Games/escape-from-tarkov/dosdevices/c:/windows/temp/win32 /home/deck/.var/app/net.lutris.Lutris/cache/winetricks/ucrtbase2019/VC_redist.x86.exe -F a10
/home/deck/.var/app/net.lutris.Lutris/cache/winetricks/ucrtbase2019/VC_redist.x86.exe: no valid cabinets found
------------------------------------------------------
warning: Note: command cabextract -q --directory=/home/deck/Games/escape-from-tarkov/dosdevices/c:/windows/temp/win32 /home/deck/.var/app/net.lutris.Lutris/cache/winetricks/ucrtbase2019/VC_redist.x86.exe -F a10 returned status 1. Aborting.
------------------------------------------------------
Monitored process exited.
Initial process has exited (return code: 256)
All processes have quit
Exit with return code 256



same issue here

**Comment by BloxedRetro** [comment] 2023-10-25 13:47
I'm having the same problem with vcrun2019, mine just says that there is a mismatch with SHA256

**Comment by Chiitoo** [comment] 2023-10-25 14:15
I'm not sure if every time I try is just a lucky time for the archive to be up, or if indeed this is more of an issue from other parts of the world, but downloading 'VC_redist.x86.exe' from the URL [1] that Winetricks is using has been working the few different times I've tried now, and the SHA matches the expected one.

1. https://web.archive.org/web/20210415064013/https://download.visualstudio.microsoft.com/download/pr/85d47aa9-69ae-4162-8300-e6b7e4bf3cf3/14563755AC24A874241935EF2C22C5FCE973ACB001F99E524145113B2DC638C1/VC_redist.x86.exe

**Comment by BloxedRetro** [comment] 2023-10-25 14:50
I'd have no idea how to manually install it. I'm a linux noob and don't know what files and folders everything would need to go under. Also, I'm trying this on a Steam Deck so I'd have to hope that my files go into the correct CompatData folder. I've had my device on for over 24-hours so I don't know if that'll dictate where my files go.

**Comment by chengstark** [comment] 2023-10-25 15:47
> I'm not sure if every time I try is just a lucky time for the archive to be up, or if indeed this is more of an issue from other parts of the world, but downloading 'VC_redist.x86.exe' from the URL [1] that Winetricks is using has been working the few different times I've tried now, and the SHA matches the expected one.
> 
> 1. https://web.archive.org/web/20210415064013/https://download.visualstudio.microsoft.com/download/pr/85d47aa9-69ae-4162-8300-e6b7e4bf3cf3/14563755AC24A874241935EF2C22C5FCE973ACB001F99E524145113B2DC638C1/VC_redist.x86.exe

Thanks! Do you know where should we put the downloaded files?

**Comment by AndnixSH** [comment] 2023-10-25 15:58
> I'm not sure if every time I try is just a lucky time for the archive to be up, or if indeed this is more of an issue from other parts of the world, but downloading 'VC_redist.x86.exe' from the URL [1] that Winetricks is using has been working the few different times I've tried now, and the SHA matches the expected one.
> 
> 1. https://web.archive.org/web/20210415064013/https://download.visualstudio.microsoft.com/download/pr/85d47aa9-69ae-4162-8300-e6b7e4bf3cf3/14563755AC24A874241935EF2C22C5FCE973ACB001F99E524145113B2DC638C1/VC_redist.x86.exe

Could it be the issue with Debian distros? because when I tried to download Arial font on Linux Mint, Ubuntu and Debian, all are getting same issue. What Linux distro are you using?

**Comment by Chiitoo** [comment] 2023-10-25 16:27
[BloxedRetro](https://github.com/BloxedRetro),

> I'd have no idea how to manually install it. I'm a linux noob and don't know what files and folders everything would need to go under. Also, I'm trying this on a Steam Deck so I'd have to hope that my files go into the correct CompatData folder. I've had my device on for over 24-hours so I don't know if that'll dictate where my files go.

I don't have any personal experience with Steam Deck, but if you can find the log file, or find the info elsewhere, I'd imagine it also downloads the file to a specific path, similar to the log in a previous post:

``` bash
Executing cd /home/deck/.var/app/net.lutris.Lutris/cache/winetricks/vcrun2019
```

So there the Winetricks cache is under `/home/deck/.var/app/net.lutris.Lutris/cache/winetricks/`.  The actual executable for vcrun would be under that `vcrun2019` directory.

[chengstark](https://github.com/chengstark),

> Thanks! Do you know where should we put the downloaded files?

See above.  : ]

[AndnixSH](https://github.com/AndnixSH),

> Could it be the issue with Debian distros? because when I tried to download Arial font on Linux Mint, Ubuntu and Debian, all are getting same issue. What Linux distro are you using?

I'm using Gentoo Linux, but I don't think that should matter, especially if you can not download the file even through that link directly using a web browser (or 'wget' or 'curl' or other).

**Comment by BloxedRetro** [comment] 2023-10-25 17:22
I'm a linux noob so I'm sorry but I don't understand what you said or how I could do it. All I really want to do is get an exe working so I can mod a video game.

**Comment by BloxedRetro** [comment] 2023-10-25 17:26
Never mind, I have found the executable for Vcrun2019 with the directory you sent. What should I do from there?

**Comment by AndnixSH** [comment] 2023-10-25 19:55
> I'm using Gentoo Linux, but I don't think that should matter, especially if you can not download the file even through that link directly using a web browser (or 'wget' or 'curl' or other).

I see. I was able to download files from archive links via browser perfectly, but sometimes the responsibility of the wayback machine's is quite slow for me. Maybe it could be the reason

**Comment by BloxedRetro** [comment] 2023-10-25 20:46
I'm gonna rephrase my last question the wording was weird.

What should I do now that I've found the executable?

**Comment by strycore** [comment] 2023-10-25 21:17
I pushed a patched version of Winetricks that fixes 2 things:

- Removed any URL to fonts hosted by Gentoo and replaced them with Github hosted files
- Added the patch from PR #2130 which solves the Archive.org downloads on Flatpak

Restart Lutris with the -f flag to force an update: `flatpak run net.lutris.Lutris -d -f`

**Comment by BloxedRetro** [comment] 2023-10-25 21:31
> > I got the same error for trying to install VC_redist.x86.exe
> 
> I also experienced this error when trying to install RDR2 and the Rockstar Games Launcher. I've found a workaround by editing the winetricks script directly, which in my case is located at `/home/$USER/.local/share/lutris/runtime/winetricks/winetricks`, and reverting back to the URLs directly from Microsoft instead of web.archive. Seems like download directly from Microsoft is working (again).
> 
> In winetricks script starting from line 13427
> 
> ```
> load_ucrtbase2019()
> {
>     w_override_dlls native,builtin ucrtbase
> 
>     # Microsoft download no longer containts ucrtbase so get the last known version from archive.org
>     #w_download https://web.archive.org/web/20210415064013/https://download.visualstudio.microsoft.com/download/pr/85d47aa9-69ae-4162-8300-e6b7e4bf3cf3/14563755AC24A874241935EF2C22C5FCE973ACB001F99E524145113B2DC638C1/VC_redist.x86.exe 14563755ac24a874241935ef2c22c5fce973acb001f99e524145113b2dc638c1
> 
>     w_download https://download.visualstudio.microsoft.com/download/pr/85d47aa9-69ae-4162-8300-e6b7e4bf3cf3/14563755AC24A874241935EF2C22C5FCE973ACB001F99E524145113B2DC638C1/VC_redist.x86.exe 14563755ac24a874241935ef2c22c5fce973acb001f99e524145113b2dc638c1
> 
>     w_try_cabextract --directory="${W_TMP}/win32"  "${W_CACHE}"/"${W_PACKAGE}"/VC_redist.x86.exe -F 'a10'
>     w_try_cabextract --directory="${W_SYSTEM32_DLLS}" "${W_TMP}/win32/a10" -F 'ucrtbase.dll'
> 
>     case "${W_ARCH}" in
>         win64)
>             # Microsoft download no longer containts ucrtbase so get the last known version from archive.org
>             #w_download https://web.archive.org/web/20210414165612/https://download.visualstudio.microsoft.com/download/pr/85d47aa9-69ae-4162-8300-e6b7e4bf3cf3/52B196BBE9016488C735E7B41805B651261FFA5D7AA86EB6A1D0095BE83687B2/VC_redist.x64.exe 52b196bbe9016488c735e7b41805b651261ffa5d7aa86eb6a1d0095be83687b2
> 
>             w_download https://download.visualstudio.microsoft.com/download/pr/85d47aa9-69ae-4162-8300-e6b7e4bf3cf3/52B196BBE9016488C735E7B41805B651261FFA5D7AA86EB6A1D0095BE83687B2/VC_redist.x64.exe 52b196bbe9016488c735e7b41805b651261ffa5d7aa86eb6a1d0095be83687b2
> 
>             w_try_cabextract --directory="${W_TMP}/win64"  "${W_CACHE}"/"${W_PACKAGE}"/VC_redist.x64.exe -F 'a10'
>             w_try_cabextract --directory="${W_SYSTEM64_DLLS}" "${W_TMP}/win64/a10" -F 'ucrtbase.dll'
>             ;;
>     esac
> }
> ```
> 
> The sha256 hash is still the same when downloading directly from Microsoft.

Do I just copy and paste this code in? I don't want to create any risks and I'm desperate to get this done as soon as possible.

**Comment by Chiitoo** [comment] 2023-10-26 07:54
I kind of forgot about having read of that 'wget2' issue.  I did reproduce the problem by manually using 'wget2' to download from the archive.

So, if everyone that are having this issue are using Flatpak and/or Lutris (or 'wget2' for some other reason), it makes a lot more sense.

[BloxedRetro](https://github.com/BloxedRetro),

> I'm gonna rephrase my last question the wording was weird.
> 
> What should I do now that I've found the executable?

Apologies for the delayed response, sleep got to me.  ^^;

If your use case is identical to the others here, I guess you might have the

`/home/deck/.var/app/net.lutris.Lutris/cache/winetricks/vcrun2019`

path as well.

You would want to put the files manually downloaded from the archive there, and then simply re-run the install.  Note that due to the issue with 'wget2', you may have a very small files there, named 'VC_redist.x86.exe' for example, and they are just text files with html in them.  The real size of that file should be around 14 MiB.

That said, if the Flatpak thingy has been modified for this, I suppose it should work after updating it, per the previous comment [1].

Flatpak and Lutris are separate projects, and I personally have no experience of using them at all, so I can not give very detailed support on using them without doing more research myself.

1. https://github.com/Winetricks/winetricks/issues/2136#issuecomment-1780069689

**Comment by Chiitoo** [comment] 2023-10-26 08:02
It seems 'wget2' got a change pushed a few days ago as well, which fixes the downloads for my testing at least:

`* src/wget.c (http_create_request): Use 'Accept: */*' for single file downloads`

- https://gitlab.com/gnuwget/wget2/-/commit/089520564f6f797c018861a520fc16e3d6aabdb4

**Comment by BloxedRetro** [comment] 2023-10-26 09:27
> Apologies for the delayed response, sleep got to me. ^^;

It's fine, dw. Sorry if I seemed pushy.

> If your use case is identical to the others here, I guess you might have the
> 
> `/home/deck/.var/app/net.lutris.Lutris/cache/winetricks/vcrun2019`
> 
> path as well.
> 
> You would want to put the files manually downloaded from the archive there, and then simply re-run the install. Note that due to the issue with 'wget2', you may have a very small files there, named 'VC_redist.x86.exe' for example, and they are just text files with html in them. The real size of that file should be around 14 MiB.
> 
> That said, if the Flatpak thingy has been modified for this, I suppose it should work after updating it, per the previous comment [1].
> 
> Flatpak and Lutris are separate projects, and I personally have no experience of using them at all, so I can not give very detailed support on using them without doing more research myself.
> 
> 1. [Web archive is down #2136 (comment)](https://github.com/Winetricks/winetricks/issues/2136#issuecomment-1780069689)

By the files, do you mean like just replace the .exe I downloaded from the link? And also would I have to install manually myself or could I run the Lutris install and it'd see that the full file is there?

**Comment by BloxedRetro** [comment] 2023-10-26 13:55
I replaced the .exe file in the cache you gave me however I'm still getting the same error as I did before when running the winetricks installation

**Comment by BloxedRetro** [comment] 2023-10-26 15:55
Can I get a response? I've been trying this for several days now and it's taking up much of the week off I have.

**Comment by AndnixSH** [comment] 2023-10-26 15:57
> I replaced the .exe file in the cache you gave me however I'm still getting the same error as I did before when running the winetricks installation

You can just run the .exe directly then install Vcrun2019, and it will be installed, just like did with the Arial32 one (Winetricks won't be able to detect if it was installed or not)

**Comment by BloxedRetro** [comment] 2023-10-26 16:00
How can I do that though since I need Winetricks to open the exe

**Comment by AndnixSH** [comment] 2023-10-26 16:05
> How can I do that though since I need Winetricks to open the exe

Double click on the exe file, just like what you do on Windows. Not sure if it works with Vcrun2019 tho

**Comment by BloxedRetro** [comment] 2023-10-26 16:12
> > How can I do that though since I need Winetricks to open the exe
> 
> Double click on the exe file, just like what you do on Windows. Not sure if it works with Vcrun2019 tho

It opens up Protontricks when I try this. Do I just find whatever game is linked under the compatdata prefix I'm using?

**Comment by AndnixSH** [comment] 2023-10-26 16:13
> Or would I open with a different program?

Open a different program and choose Wine

**Comment by BloxedRetro** [comment] 2023-10-26 16:19
I don't think I have wine

**Comment by AndnixSH** [comment] 2023-10-26 16:27
> I only have Lutris

Oh. Try selecting Lutris from the "Open with..." dialog. If it's not there, maybe try adding exe in Lutris interface and run from there. I'm sadly not familar with it. With Wine, you can run .exe directly

![image](https://github.com/Winetricks/winetricks/assets/40742924/65cd5760-57f9-4958-8d21-0e980d04cb8b)

**Comment by BloxedRetro** [comment] 2023-10-26 16:34
> > I only have Lutris
> 
> Oh. Try selecting Lutris from the "Open with..." dialog. If it's not there, maybe try adding exe in Lutris interface and run from there. I'm sadly not familar with it. With Wine, you can run .exe directly
> 
> ![image](https://user-images.githubusercontent.com/40742924/278411031-65cd5760-57f9-4958-8d21-0e980d04cb8b.png)

I've just downloaded Wine. Should it work out of the box or should I not risk it and simply go with Lutris?

**Comment by BloxedRetro** [comment] 2023-10-26 16:50
It says that setup is successful but the application I am trying to run is still failing. Not sure if this is the reason though. Somebody mentioned about the temp folders being blocked. Would a prefix contain temp folders if anyone knows?

**Comment by Chiitoo** [comment] 2023-10-26 16:59
[BloxedRetro](https://github.com/BloxedRetro), at this point it would most likely be best if you tried the Lutris support chennels, such as their forums [1].

I'm sure there will be a lot more people that will be able to assist you, on top of being more familiar with your particular set-up.  :  ]

This issue tracker is not meant for "live support" like this, especially when it's not exactly about Winetricks itself alone.

1. https://forums.lutris.net/

**Comment by BloxedRetro** [comment] 2023-10-26 17:10
I put my game directory in there but now IT'S GONE

I can't find the game files at all. Is that normal for Lutris or Steam to do? Every other file seems fine.

**Comment by BloxedRetro** [comment] 2023-10-26 17:10
Literally everything else but what I wanted to do is working now.

**Comment by strycore** [comment] 2023-10-27 20:23
That's because you restarted Lutris and got the updated version of Winetricks.

**Closed** 2023-12-30 10:30 UTC

**Comment by kenorb** [comment] 2024-01-03 15:07
> od: wine: No such file or directory

For this error, follow-up: GH-2143.
