### ISSUE TITLE
Failed installation reported using 32bit WINEPREFIX if default is 64bit

### ISSUE THREAD

**Issue by NHellFire** [Winetricks/winetricks#717] opened 2017-01-17 12:40 UTC
False installation failures are reported in cases where the default WINEPREFIX is 64bit, but you're working on a 32bit WINEPREFIX.

Example using mdac28 (with some extra info output added):
```
$ winetricks prefix=wine32 mdac28
WINEPREFIX is now /home/nathan/.wine
W_COMMONFILES_X86_WIN=C:\Program Files (x86)\Common Files
------------------------------------------------------
You are using a 64-bit WINEPREFIX. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20170101 - sha1sum: 878c122699f1b4873329ca788ffcb7de2d19b025 with wine-1.8.5 (Ubuntu 1.8.5-1ubuntu1) and WINEARCH=win64
WINEPREFIX is now /home/nathan/.local/share/wineprefixes/wine32
W_COMMONFILES_X86_WIN=C:\Program Files\Common Files
Executing w_do_call mdac28
Executing load_mdac28 
Using native,builtin override for following DLLs: odbc32 odbccp32 oledb32
Executing winetricks_early_wine regedit C:\windows\Temp\_mdac28\override-dll.reg
Setting Windows version to nt40
Executing winetricks_early_wine regedit C:\windows\Temp\_mdac28\set-winver.reg
Executing cd /home/nathan/.cache/winetricks/mdac28
Executing wine mdac_typ.exe
err:richedit:ReadStyleSheet skipping optional destination
err:richedit:ReadStyleSheet skipping optional destination
err:richedit:ReadStyleSheet skipping optional destination
err:richedit:ReadStyleSheet skipping optional destination
err:richedit:ReadStyleSheet skipping optional destination
Setting Windows version to winxp
Executing winetricks_early_wine regedit C:\windows\Temp\_mdac28\set-winver.reg
------------------------------------------------------
mdac28 install completed, but installed file /home/nathan/.local/share/wineprefixes/wine32/dosdevices/c:/Program Files (x86)/Common Files/System/ADO/msado27.tlb not found
------------------------------------------------------
```

This is caused by the metadata being loaded before the prefix argument is processed, so any environment variables used in the metadata are from the default WINEPREFIX.
Not sure what the best/easiest way to fix this would be.

Workaround would be to use `WINEPREFIX=~/.local/share/wineprefixes/wine32 winetricks` instead of `winetricks prefix=wine32`

**Comment by austin987** [comment] 2017-01-17 14:46
I assume you're installing via the GUI / select WINEPREFIX, right?

**Comment by NHellFire** [comment] 2017-01-17 15:14
Command line. But using the GUI and choosing my 32bit WINEPREFIX has the same result, since the metadata (including the files that it checks for after install) are loaded *before* selecting the prefix.

**Comment by Chiitoo** [comment] 2017-01-17 22:45
As a sidey-note, the github-flavoured markdown ate the first line of the code block due to the backticks being on the same line as the content (I only noticed due to the plain-text e-mails I get.

That is, here are the true first two lines:

```
$ winetricks prefix=wine32 mdac28
WINEPREFIX is now /home/nathan/.wine
```

**Comment by NHellFire** [comment] 2017-01-18 06:20
Oops, fixed that now

**Comment by austin987** [comment] 2017-01-18 07:09
@NHellFire your explanation makes sense, but I can't seem to reproduce this locally. I've written a short test script that as I understand the bug, should reproduce it. Does it trigger it for you? If not, maybe you can point out what's wrong with my testcase..

```
#!/bin/bash
# For testing https://github.com/Winetricks/winetricks/issues/717
set -e
set -u
set -x

export WIN32_PREFIX="$HOME/.local/share/wineprefixes/wine32"
export DEFAULT_PREFIX="$HOME/.wine"
export WINEARCH=""
export WINEPREFIX=""

# Kill processes/cleanup/bootstrap prefixes:
# also wineboot prefixes so we can ensure WINEARCH is what we want:
for prefix in "$WIN32_PREFIX" "$DEFAULT_PREFIX" ; do
    WINEPREFIX="$prefix" wineserver -k || true
    rm -rf "$WIN32_PREFIX" "$DEFAULT_PREFIX"

    case "$prefix" in
        "$WIN32_PREFIX")  arch="win32" ;;
        "$DEFAULT_PREFIX") arch="win64" ;;
        *) echo "error: unknown prefix $WINEPREFIX!" ; exit 1 ;;
    esac

    WINEARCH="$arch" WINEPREFIX="$prefix" wineboot
done

# Now, try to reproduce the bug:
unset WINEPREFIX
winetricks -q prefix=wine32 mdac28

```

**Comment by NHellFire** [comment] 2017-01-18 07:37
Cleaning up the prefixes needs to be outside the for loop, otherwise the 32bit gets created, then deleted, then recreated as 64bit when winetricks runs. After that change, the script triggers the bug.

**Comment by austin987** [comment] 2017-01-18 07:43
Nice, thanks. I can see it now with:

```
#!/bin/bash

set -e
set -u
set -x

export WIN32_PREFIX="$HOME/.local/share/wineprefixes/wine32"
export DEFAULT_PREFIX="$HOME/.wine"
export WINEARCH=""
export WINEPREFIX=""

# Kill processes/cleanup/bootstrap prefixes:
# also wineboot prefixes so we can ensure WINEARCH is what we want:
for prefix in "$WIN32_PREFIX" "$DEFAULT_PREFIX" ; do
    WINEPREFIX="$prefix" wineserver -k || true
    rm -rf "$prefix"

    case "$prefix" in
        "$WIN32_PREFIX")  arch="win32" ;;
        "$DEFAULT_PREFIX") arch="win64" ;;
        *) echo "error: unknown prefix $WINEPREFIX!" ; exit 1 ;;
    esac

    WINEARCH="$arch" WINEPREFIX="$prefix" wineboot
done

# Now, try to reproduce the bug:
unset WINEPREFIX
winetricks -q prefix=wine32 mdac28
```

I'll look tomorrow, probably

**Comment by austin987** [comment] 2017-01-24 07:25
Quick update: I took a look today, the issue is set_wineprefix gets called a few places, and that wasn't taken into account with prefix=foo. I'm still looking at how to handle this.

**Comment by austin987** [comment] 2019-11-07 12:33
Took a bit longer than I thought, but could you try https://github.com/Winetricks/winetricks/pull/1418 please?

**Comment by austin987** [comment] 2019-11-27 18:15
#1418 was committed and this now works for me; please reopen if you're still having issues.

**Closed by austin987** 2019-11-27 18:15 UTC
Labels: win64

**Comment by mirh** [comment] 2020-01-19 17:21
Between 20190912 and 20191224 this actually regressed for me. 
Ie6 was working fine before this, now I'm constantly pissed off by this "you must use winearch=win32" error.

**Comment by austin987** [comment] 2020-01-24 05:27
Please open a dedicated issue for that, with instructions to reproduce (and ideally run a regression test to figure out what broke it).
