### ISSUE TITLE
vcrun2015, gfw and vcrun6 fail to install with status 53.

### ISSUE THREAD

**Issue by GeekyGami** [Winetricks/winetricks#1778] opened 2021-06-15 00:09 UTC
This has been going on for a long time, but has yet to be fixed.
It happened on every version of Wine I've used.

I'm currently on the latest staging version available on Manjaro,
6.6 -291 - g788fd4ee44f

For vcrun2015, import_dll library is failing to find multiple DLLs over and over again, a veritable curtain of error messages.
VCrun6 does the same exact thing.
Upon further inspection, so does GFW.

I've made sure to --self-update Winetricks.

**Comment by gverm** [comment] 2021-06-15 14:48
For me with wine-git these don't fail. A lot of loader regressions were fixed in later versions of wine.
Do note that vcrun6 will still cause prefix breakage due to same problem as #1756.

**Comment by akadaedalus** [comment] 2021-08-24 15:57
My wine prefix was rendered broken by this too, even after I upgraded winetricks.  I can confirm that the git version works on a new prefix.  I'm not looking forward to reinstalling everything.  

I recommend releasing a new version soon so the distros will pick it up.

**Comment by austin987** [comment] 2021-08-31 05:26
vcrun6 is fixed by https://github.com/Winetricks/winetricks/commit/c03988712b09fdaf8d0e5aa7914956e76f3c9e80

**Closed by austin987** 2021-08-31 05:26 UTC

**Comment by Joe23232** [comment] 2021-12-06 07:59
@austin987 How would I get the fixed version?

**Comment by man-of-eel** [comment] 2021-12-06 19:30
how can i fix my broken wineprefix after installing the broken vcrun6?
