### ISSUE TITLE
Installation of .NET 3.0 (dotnet30) fails on Fedora 24

### ISSUE THREAD

**Issue by Phidica** [Winetricks/winetricks#700] opened 2016-11-25 18:48 UTC
Using the Wine and Winetricks versions provided by the Fedora repos as follows.
Wine: wine-1.9.23 (Staging)
Winetricks: 20161005 - sha1sum: `eb7868b98a664744f033a98f22179ff797bde56a`

As far as I can tell, this is *unrelated* to the currently open #677 

Steps to reproduce
===============
1. Using fresh wineprefix,
`WINEPREFIX=~/.wine32-dotnetTest WINEARCH=win32 winetricks -q dotnet30`

Result
=====
[Full output (pastebin)](http://pastebin.com/FU5DWUbH)

To summarise, I think the important parts are:
```
err:eventlog:ReportEventW L"System.ArgumentException: Item has already been added. Key in dictionary: 'no_proxy'  Key being added: 'no_proxy'\r\n   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)\r\n   at System.Collections.Hashtable.Add(Object key, Object value)\r\n   at System.Collections.Specia"...
err:msi:ITERATE_Actions Execution halted, action L"DD_CA_InstallXwsRegExe_X86.3643236F_FC70_11D3_A536_0090278A1BB8" returned 1603
err:eventlog:ReportEventW L"System.ArgumentException: Item has already been added. Key in dictionary: 'no_proxy'  Key being added: 'no_proxy'\r\n   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)\r\n   at System.Collections.Hashtable.Add(Object key, Object value)\r\n   at System.Collections.Specia"...
------------------------------------------------------
Note: command wine dotnetfx3.exe /q /c:install.exe /q returned status 67.  Aborting.
------------------------------------------------------
```
but I'm no expert, so don't take this opinion with too much weight

Furthermore, it appears that running *any* dotnetXX recipe higher than dotnet30 also fails at the .NET 3.0 installation step

Additional tests
============
Also tested with the latest Winetricks (20161107 - sha1sum: `ee6251b73e02901cf09738419cd3ae973749770f`) and same behaviour is observed

**Comment by austin987** [comment] 2016-12-18 06:55
Sorry for the late reply.

I don't regularly use/test staging, so it's possible this is a staging issue. However, the no_proxy bit is interesting. Out of curiosity, are you using a proxy?

**Comment by Rhotias** [comment] 2016-12-19 16:45
No, I don't use a proxy

**Comment by Beeblebrox-BSD** [comment] 2016-12-19 20:41
All the mirrors for 3.0 seem down, confirmed with browser. Might it have been renamed? I came accross "NetFx30SP1_x86.exe" which is available.

$ winetricks dotnet45
Using winetricks 20161107 - sha1sum: 3d19f41a098a87bb66f097f5a825c39b65f2e2ce with wine-2.0-rc1
<...stuff...>
Executing load_dotnet30 
Downloading http://download.microsoft.com/download/3/F/0/3F0A922C-F239-4B9B-9CB0-DF53621C57D9/dotnetfx3.exe to ~/.cache/winetricks/dotnet30
--2016-12-19 23:30:21--  http://download.microsoft.com/download/3/F/0/3F0A922C-F239-4B9B-9CB0-DF53621C57D9/dotnetfx3.exe
Resolving download.microsoft.com (download.microsoft.com)... 23.78.59.89
Connecting to download.microsoft.com (download.microsoft.com)|23.78.59.89|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-12-19 23:30:22 ERROR 404: Not Found.

Downloading https://web.archive.org/web/http://download.microsoft.com/download/3/F/0/3F0A922C-F239-4B9B-9CB0-DF53621C57D9/dotnetfx3.exe to ~/.cache/winetricks/dotnet30
--2016-12-19 23:30:24--  https://web.archive.org/web/http://download.microsoft.com/download/3/F/0/3F0A922C-F239-4B9B-9CB0-DF53621C57D9/dotnetfx3.exe
Resolving web.archive.org (web.archive.org)... 207.241.225.186
Connecting to web.archive.org (web.archive.org)|207.241.225.186|:443... connected.
Unable to establish SSL connection.
------------------------------------------------------
Downloading https://web.archive.org/web/http://download.microsoft.com/download/3/F/0/3F0A922C-F239-4B9B-9CB0-DF53621C57D9/dotnetfx3.exe failed
------------------------------------------------------

**Comment by slyscorpion** [comment] 2016-12-19 21:42
https://web.archive.org/web/http://download.microsoft.com/download/3/F/0/3F0A922C-F239-4B9B-9CB0-DF53621C57D9/dotnetfx3.exe  

That link still works for me, I just clicked it and it's downloading the installer...

**Comment by Rhotias** [comment] 2016-12-20 08:04
I have successfully installed .NET 4 in the past, so all the installers are in my cache and Winetricks has been using those during my tests. I just cleared my cache and ran the steps as in my report, and fresh installers were downloaded from `https://web.archive.org/web/http://download.microsoft.com/download/3/F/0/3F0A922C-F239-4B9B-9CB0-DF53621C57D9/dotnetfx3.exe` and `http://download.lenovo.com/ibmdl/pub/pc/pccbbs/thinkvantage_en/dotnetfx.exe`. The final result was the same as before

**Comment by Beeblebrox-BSD** [comment] 2016-12-28 10:17
I think the webarchive.org site is blocking users based on IP range. I was able to download the file by using a tunnel with exit point in the US.
Thanks and regards.

**Comment by austin987** [comment] 2016-12-28 10:34
You can use the --torify option if you have torify installed

**Comment by Beeblebrox-BSD** [comment] 2016-12-28 10:37
Cool! Nice to know - thanks

**Comment by austin987** [comment] 2017-01-21 08:48
This works for me with wine-staging 2.0-rc5 and winetricks HEAD, could you retry?

**Comment by gso** [comment] 2017-02-14 15:09
A quick note, I have the same problem by the looks installing dotnet452:

------------------------------------------------------
Note: command wine dotnetfx3.exe /q /c:install.exe /q returned status 67.  Aborting.
------------------------------------------------------

Ubuntu 16.04.2 i386 (32 bit)
wine-staging (2.1)
winetricks 20170207

**Comment by MikeRich88** [comment] 2017-04-29 22:25
This link works for me.

http://web.archive.org/web/2011/http://download.microsoft.com/download/3/F/0/3F0A922C-F239-4B9B-9CB0-DF53621C57D9/dotnetfx3.exe

It looks like Winetricks is trying Web Archive without any date infomation, so they send the latest version that they have on had of a file - and the latest "revision" is the file not existing (which they dutifully archive). And it seems that  many of these revisions are the same too - non existance. 

The chain of redirections goes like this:

https://web.archive.org/web/https://download.microsoft.com/download/3/F/0/3F0A922C-F239-4B9B-9CB0-DF53621C57D9/dotnetfx3.exe
https://web.archive.org/web/2/https://download.microsoft.com/download/3/F/0/3F0A922C-F239-4B9B-9CB0-DF53621C57D9/dotnetfx3.exe
https://web.archive.org/web/20170118155823/http://download.microsoft.com/download/3/F/0/3F0A922C-F239-4B9B-9CB0-DF53621C57D9/dotnetfx3.exe (404 ERROR)

Notice they send you to 2017 file... but that file is gone.

I tried every year and finaly got a download with 2011, but I was also able to get a download using a specific 2014 URL that I got from their web interface. This makes me wonder if the file's availability came and went over the course of a year.

https://web.archive.org/web/2011/https://download.microsoft.com/download/3/F/0/3F0A922C-F239-4B9B-9CB0-DF53621C57D9/dotnetfx3.exe
https://web.archive.org/web/20120104121749/http://download.microsoft.com/download/3/F/0/3F0A922C-F239-4B9B-9CB0-DF53621C57D9/dotnetfx3.exe (200 OK, downloads 52770576 bytes, MD5 hash is 7b26435437e8d779ff0084d4ea96d15a which seems to be right after a peek at Google)

I also tried the oldest possible date which  is 1996 in Web Archive. They send me to the first copy of the file taken in 2006. Same file size and hash. I'm assumine Winetricks has a hash of some kind of the expected file. Combine with some heuristics or manipulaton of Webarchive to fix the  downloads. 

I don't think it is web archive doing blocking as I already have a US IP address.

Hope that helps.

**Comment by qwertychouskie** [comment] 2017-04-30 00:23
The merging of https://github.com/Winetricks/winetricks/pull/775 should have fixed this, so updating should fix your issue.

**Comment by Phidica** [comment] 2017-05-01 12:51
@austin987 and @qwertychouskie: I have retried now (wine-2.0 staging and latest winetricks 20170327-next sha256sum: `c27f14651a9e0c3fb1d8b9dfd18777cccabe3b37d19553e200b4cf7bc90fcaa2`). I deleted my winetricks cache before attempting to run the command I gave in my initial post. New versions of the installers were downloaded, and the `dotnetfx3.exe` MD5 hash matches that specified by @MikeRich88 in the above post. The full installation output is [here](https://pastebin.com/CmiQ6s8q) and unfortunately seems to be much the same as before

Also just noticed I never specified my Fedora version: 24

**Comment by qwertychouskie** [comment] 2017-05-01 16:42
2.0-staging?  If you are using Staging, you should be using 2.6.

**Comment by Phidica** [comment] 2017-05-02 09:55
I'm using the latest wine provided in the Fedora 24 updates repo, which is wine-2.0 staging. I expect something closer to 2.6 is in the Fedora 25 repos but I have been putting off upgrading for various reasons. Since F24 will reach end-of-life in a few months, I will see if I can upgrade some time soon and try again

**Comment by qwertychouskie** [comment] 2017-05-02 18:22
Or use the official WineHQ repo (https://wiki.winehq.org/Fedora):

    dnf config-manager --add-repo https://dl.winehq.org/wine-builds/fedora/24/winehq.repo
    dnf install winehq-staging

**Comment by solismanuel** [comment] 2017-07-24 23:51
Hello, All

I have tested in both FreeBSD and Devuan since i want to run a windows program from work.

The versions are:

- [ ] OS1  >>>   FREEBSD 11.0-RELEASE-p1 FreeBSD 11.0-RELEASE-p1 #0 r306420: Thu Sep 29 01:43:23 UTC 2016     root@releng2.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
wine  >>>  wine 2.10
winetricks >>> 20170614 - sha256sum: e641a983e0f9be2602d512292966d07932118ce71354d4ce058847725bfc8fbd
Note: command wine dotnetfx3.exe /q /c:install.exe /q returned status 67.  Aborting.
_Commands_
`rm -rf .wine`
`winecfg`
`winetricks mfc40`
`winetricks corefonts vcrun6`
`winetricks dotnet35`
**DOES NOT WORK!**  

- [ ] OS2 >>>  DEVUAN Linux devuan 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u2 (2017-06-26) x86_64 GNU/Linux
wine >>>  wine-1.6.2
winetricks >>> 20140817 - sha1sum: fb1d7184dc186313cf26e1a65a8e6ff3c5fadc50
_Commands_
`rm -rf .wine`
`winecfg`
`winetricks corefonts vcrun6`
`winetricks dotnet35`
**IT WORKS!!**

I assumed that there would be a clear difference in the way that different versions of winetricks installed the packages so the order is:
**Order of installed packages in OS2 Devuan**
In `winetricks 20140817`:

> remove mono
> install dotnet20
> install netframework3
> install dotnet20sp1
> install xps essentials pack
> install dotnet30sp1
> install msxml3
> install dotnet35

**Order of installed packages in OS1 FreeBSD**
In `winetricks 20170614`:

> remove mono
> install dotnet20
> install dotnet30 >> FAIL!! 

when i run `wine .cache/winetricks/dotnet30/dotnetfx3.exe` the error showed is:

> [07/24/17,13:23:51] Windows Communication Foundation: [2] Error: Installation failed for component Windows Communication Foundation. MSI returned error code 1603
> [07/24/17,13:23:59] WapUI: [2] DepCheck indicates Windows Communication Foundation is not installed.

So i pressumed that `error 67` could be related to the _Windows Communication Foundation_ but if i try to install any new program and restart `winetricks dotnet35` i got a conflict that says that i have installed dotnet20, that does not happend in the older version of winetricks.

Anyways, i am still stuck in this problem, could anyone give more ideas??????

Thank you

Manuel

**Comment by austin987** [comment] 2017-07-25 04:15
Comparing different OSs, different wine versions, and different winetricks versions isn't terribly helpful at narrowing down the problem..

**Comment by solismanuel** [comment] 2017-07-25 05:25
Sorry mr @austin987  (by the way, thank you for your great support)

I know that i looks so messy but it helped me to understand the problem, since I had to try in that OSs at hand.
I think that me asking shoot would be to FreeBSD 11, wine 2.10 and winetricks 20170614
To reproduce the error, the following commands are executed:
`rm -rf .wine`
`winecfg`
`winetricks mfc40 corefonts vcrun6`
`winetricks dotnet35`

> Note: command wine dotnetfx3.exe /q /c:install.exe /q returned status 67. Aborting.

After trying `wine .cache/winetricks/dotnet30/dotnetfx3.exe /q /c:install.exe /q` i noticed that the main issue is `error 1603`

Looking in the web, it seems that somehow the installer does not have the permissions or the complete access to a determined program (in case of dotnet30 is the WCF, in case of dotnet35 is .Net3.0a both with error code 1603)

[https://support.microsoft.com/en-us/help/834484/you-receive-an-error-1603-a-fatal-error-occurred-during-installation-e](url)

The Windows users came across this problem by uninstalling IIS, so maybe there is a register that should be modified or so.

Thanks again for your support and contribution to the project :D
If you want me to send more information please tell me, i will be more than happy to help.

Manuel
PS i know i am not doing right (pretty garbage actually), but in the mean time what i do is to prepare my prefix in Devuan with dotnet35 and dotnet40 and then move it to FreeBSD to continue working. (Sorry for that but i hope we could find a better solution)

**Comment by austin987** [comment] 2017-07-25 05:47
Just a wildshot hack to try for those affected

```
#!/bin/bash
taskset -c 0 wine "$@"
```

put that in a file, call it wine-wrapper, then do:
```
chmod +x wine-wrapper
export WINE="$PWD/wine-wrapper"
winetricks -q foo
```

and see if that helps (be sure to install taskset if you don't have it).

**Comment by solismanuel** [comment] 2017-07-25 06:54
In FreeBSD there is no `taskset` so the file contained:
```
#!/usr/local/bin/bash
sudo cpuset -l 0 wine "$@"
```

then i followed:
```
chmod +x wine-wrapper
export WINE="$PWD/wine-wrapper"
rm -rf .wine
winecfg
winetricks dotnet35  (i did not use the -q option to see the whole picture)
```
It stopped after installing dotnet20 
here is the error:

```
 Setting Windoes version to winxp
Executing winetricks_early_wine regedit C: windows Temp _dotnet20 set-winver.reg
regedit: The file 'C: windows Temp _dotnet20 set-winver.reg' was not found
 ------------------------------------------------------------
 dotnet20 install completed, but installed file /home/user/dosdevices/c:/windows/Microsoft.NET/Framework/v2.0.50727/Microsoft .NET Framework 2.0/install.exe not found
 --------------------------------------------------------------
```

(note: when using the `wine-wrapper` it "repairs" the dotnet20, without the `wine-wrapper` it "installs" it)

maybe i am using the bad alternative to `taskset` :S

**Comment by solismanuel** [comment] 2017-07-25 19:05
Update,
I just tried again in a FreeBSD 11.0 r p1 i386, wine-2.10, winetricks 20170614-next 
With the same results.
Maybe that test emulate the taskset in FBSD amd64

**Comment by allentiak** [comment] 2017-08-26 06:01
If you use this (dated) download link, the 404 is gone :-)

http://web.archive.org/web/20111009103305/https://download.microsoft.com/download/3/F/0/3F0A922C-F239-4B9B-9CB0-DF53621C57D9/dotnetfx3.exe

**Comment by servel333** [comment] 2017-09-22 03:31
> http://web.archive.org/web/20111009103305/https://download.microsoft.com/download/3/F/0/3F0A922C-F239-4B9B-9CB0-DF53621C57D9/dotnetfx3.exe

Confirmed this URL works and solved my problem with Ubuntu and PlayOnLinux winetricks.

**Comment by austin987** [comment] 2017-09-25 06:00
@solismanuel, would you mind opening a separate issue about taskset/cpuset so it doesn't get lost? Thanks.

**Comment by austin987** [comment] 2017-10-12 06:07
@solismanuel https://github.com/Winetricks/winetricks/commit/2dcf55e9ee3d7446e297ef78086c4083df7c1904

**Comment by solismanuel** [comment] 2017-10-13 11:43
sorry for my late response, i was out of town (in Moscu, with my parents in love, so no internet)
i see that you already opened it, so i guess there is nothing to do there.
(i will try to continue where i was left with dotnet30)

**Comment by austin987** [comment] 2018-12-04 02:39
It's been a year, and I think this has been fixed anyway. Reopen if it's still a problem in winetricks master / current wine.

**Closed by austin987** 2018-12-04 02:39 UTC
Labels: dotnet, download, wine-staging
