### ISSUE TITLE
Issue with takao font (So takao, ckjfont & corefonts)

### ISSUE THREAD

**Issue by Mo0x** [Winetricks/winetricks#576] opened 2015-11-26 00:15 UTC
xecuting w_do_call takao
Executing load_takao
Executing mkdir -p /Users/Max/.cache/winetricks/takao
Downloading http://launchpad.net/takao-fonts/003.02/003.02.01/+download/takao-fonts-ttf-003.02.01.zip to /Users/Max/.cache/winetricks/takao
--2015-11-26 00:47:43--  http://launchpad.net/takao-fonts/003.02/003.02.01/+download/takao-fonts-ttf-003.02.01.zip
Résolution de launchpad.net (launchpad.net)… 91.189.89.222, 91.189.89.223
Connexion à launchpad.net (launchpad.net)|91.189.89.222|:80… connecté.
requête HTTP transmise, en attente de la réponse… 404 Not Found
2015-11-26 00:47:43 erreur 404 : Not Found.

------------------------------------------------------
Downloading http://launchpad.net/takao-fonts/003.02/003.02.01/+download/takao-fonts-ttf-003.02.01.zip failed
------------------------------------------------------

The probleme is there : http://launchpad.net/takao-fonts/003.02/003.02.01/+download/takao-fonts-ttf-003.02.01.zip, this is not the good url, the good one is http://launchpad.net/takao-fonts/trunk/003.02.01/+download/takao-fonts-ttf-003.02.01.zip.
In the winetricks file the url is ok i don't why this happen.

Is there a possibility to manually download the file and run a modified wintricks file which instead of "w_download  http://launchpad.net/takao-fonts/trunk/003.02.01/+download/takao-fonts-ttf-003.02.01.zip. 44etc..." take directly the pre-downloaded file ? I'm such a newbie so i can't do it myself because i don't understand what the 4444 (e.g big number's string) actually do ...

**Comment by austin987** [comment] 2015-11-30 04:38
Duplicate of Issue 489

**Closed by austin987** 2015-11-30 04:38 UTC

**Comment by austin987** [comment] 2015-11-30 04:40
The string is a sha1sum of the installer, to make sure we have the right file (and it wasn't modified/corrupted, or if we change mirrors). If only the URL changed, simply changing the URL is enough. If that doesn't work, it's likely that the sha1sum changed which you should manually verify.
