### ISSUE TITLE
mdac28 not installing

### ISSUE THREAD

**Issue by Tubbles** [Winetricks/winetricks#1061] opened 2018-07-27 09:03 UTC
I have just tried this, from a fresh install of wine on arch linux rolling release:

`WINEARCH=win32 WINEPREFIX=~/.wine-circuitmaker winetricks -q gdiplus corefonts riched20 mdac28 msxml6 dotnet40`
```
...
Executing wine mdac_typ.exe /q /C:setup /qnt
0055:fixme:setupapi:SetupAddInstallSectionToDiskSpaceListA Stub
0055:fixme:setupapi:SetupAddInstallSectionToDiskSpaceListA Stub
0055:fixme:setupapi:SetupAddInstallSectionToDiskSpaceListA Stub
0055:fixme:setupapi:SetupAddInstallSectionToDiskSpaceListA Stub
0055:fixme:setupapi:SetupAddInstallSectionToDiskSpaceListA Stub
0055:fixme:setupapi:SetupAddInstallSectionToDiskSpaceListA Stub
0055:fixme:setupapi:SetupAddInstallSectionToDiskSpaceListA Stub
0055:fixme:setupapi:SetupAddInstallSectionToDiskSpaceListA Stub
0055:fixme:setupapi:SetupAddInstallSectionToDiskSpaceListA Stub
0055:fixme:setupapi:SetupAddInstallSectionToDiskSpaceListA Stub
0055:fixme:setupapi:SetupAddInstallSectionToDiskSpaceListA Stub
0055:fixme:setupapi:SetupAddInstallSectionToDiskSpaceListA Stub
0055:fixme:setupapi:SetupAddInstallSectionToDiskSpaceListA Stub
0055:fixme:setupapi:SetupAddInstallSectionToDiskSpaceListA Stub
0055:fixme:setupapi:SetupAddInstallSectionToDiskSpaceListA Stub
0055:fixme:setupapi:SetupAddInstallSectionToDiskSpaceListA Stub
0055:fixme:setupapi:SetupAddInstallSectionToDiskSpaceListA Stub
0055:fixme:setupapi:SetupAddInstallSectionToDiskSpaceListA Stub
0055:fixme:setupapi:SetupAddInstallSectionToDiskSpaceListA Stub
0055:fixme:setupapi:SetupAddInstallSectionToDiskSpaceListA Stub
0055:fixme:setupapi:SetupAddInstallSectionToDiskSpaceListA Stub
0055:fixme:setupapi:extract_cabinet_file awful hack: extracting cabinet "C:\\users\\monkey\\Temp\\IXP000.TMP\\msvcrt.CAB"
0055:fixme:setupapi:extract_cabinet_file awful hack: extracting cabinet "C:\\users\\monkey\\Temp\\IXP000.TMP\\mtxfiles.CAB"
0055:fixme:setupapi:extract_cabinet_file awful hack: extracting cabinet "C:\\users\\monkey\\Temp\\IXP000.TMP\\MDACxpak.CAB"
0055:fixme:setupapi:SetupDefaultQueueCallbackW notification 262144 params 32f2ec,0
0055:fixme:setupapi:extract_cabinet_file awful hack: extracting cabinet "C:\\users\\monkey\\Temp\\IXP000.TMP\\MDACxpak.CAB"
0055:fixme:setupapi:extract_cabinet_file awful hack: extracting cabinet "C:\\users\\monkey\\Temp\\IXP000.TMP\\MDACxpak.CAB"
0055:err:setupapi:SetupDefaultQueueCallbackW copy error 32 L"C:\\users\\monkey\\Temp\\IXP000.TMP\\msdaorar.dll" -> L"C:\\Program Files\\Common Files\\System\\OLE DB\\msdaorar.dll"
------------------------------------------------------
Note: command wine mdac_typ.exe /q /C:setup /qnt returned status 5. Aborting.
------------------------------------------------------
0015:err:service:process_send_command receiving command result timed out
0029:err:plugplay:handle_bus_relations Failed to load driver L"WineHID"
*** stack smashing detected ***: <unknown> terminated
wine: Assertion failed at address 0xf7ff1de9 (thread 000f), starting debugger...
000f:err:seh:start_debugger Couldn't start debugger ("winedbg --auto 14 156") (1115)
Read the Wine Developers Guide on how to set up winedbg or another debugger
```

Best regards,
~Tubbles

**Comment by Tubbles** [comment] 2018-07-27 10:06
To reproduce:
`WINEARCH=win32 WINEPREFIX=~/.wine-circuitmaker winetricks mdac28`

Versions:
winetricks: `20180603 - sha256sum: cad4e699f55c297afe5b177d68dccf1ef54e9dd23518a6f6343caa0ab7636615`
wine: `wine-3.13`

**Comment by Tubbles** [comment] 2018-07-27 10:29
Halting the installation in the GUI shows that the file `msdaorar.dll` seems to be missing from the temp directory

**Comment by austin987** [comment] 2018-07-27 20:36
Works fine here:
```
austin@austin2:~$ wineserver -k ; rm -rf ~/.wine ; WINEARCH=win32 winetricks -q mdac28 ; echo $?
Using winetricks 20180603-next - sha256sum: 4035b5cf1fd478d27f390b0c2d3f310d7334bd16484e6ca70396e333369a7052 with wine-3.13 and WINEARCH=win32
Executing w_do_call mdac28
Executing load_mdac28 
Using native,builtin override for following DLLs: mtxdm odbc32 odbccp32 oledb32
Executing wine regedit /S C:\windows\Temp\_mdac28\override-dll.reg
Setting Windows version to nt40
Executing wine regedit /S C:\windows\Temp\_mdac28\set-winver.reg
Executing cd /home/austin/.cache/winetricks/mdac28
Executing wine mdac_typ.exe /q /C:setup /qnt
0069:err:richedit:ReadStyleSheet skipping optional destination
0069:err:richedit:ReadStyleSheet skipping optional destination
0069:err:richedit:ReadStyleSheet skipping optional destination
0069:err:richedit:ReadStyleSheet skipping optional destination
0069:err:richedit:ReadStyleSheet skipping optional destination
0069:fixme:setupapi:SetupAddInstallSectionToDiskSpaceListA Stub
0069:fixme:setupapi:SetupAddInstallSectionToDiskSpaceListA Stub
0069:fixme:setupapi:SetupAddInstallSectionToDiskSpaceListA Stub
0069:fixme:setupapi:SetupAddInstallSectionToDiskSpaceListA Stub
0069:fixme:setupapi:SetupAddInstallSectionToDiskSpaceListA Stub
0069:fixme:setupapi:SetupAddInstallSectionToDiskSpaceListA Stub
0069:fixme:setupapi:SetupAddInstallSectionToDiskSpaceListA Stub
0069:fixme:setupapi:SetupAddInstallSectionToDiskSpaceListA Stub
0069:fixme:setupapi:SetupAddInstallSectionToDiskSpaceListA Stub
0069:fixme:setupapi:SetupAddInstallSectionToDiskSpaceListA Stub
0069:fixme:setupapi:SetupAddInstallSectionToDiskSpaceListA Stub
0069:fixme:setupapi:SetupAddInstallSectionToDiskSpaceListA Stub
0069:fixme:setupapi:SetupAddInstallSectionToDiskSpaceListA Stub
0069:fixme:setupapi:SetupAddInstallSectionToDiskSpaceListA Stub
0069:fixme:setupapi:SetupAddInstallSectionToDiskSpaceListA Stub
0069:fixme:setupapi:SetupAddInstallSectionToDiskSpaceListA Stub
0069:fixme:setupapi:SetupAddInstallSectionToDiskSpaceListA Stub
0069:fixme:setupapi:SetupAddInstallSectionToDiskSpaceListA Stub
0069:fixme:setupapi:SetupAddInstallSectionToDiskSpaceListA Stub
0069:fixme:setupapi:SetupAddInstallSectionToDiskSpaceListA Stub
0069:fixme:setupapi:SetupAddInstallSectionToDiskSpaceListA Stub
0069:fixme:setupapi:extract_cabinet_file awful hack: extracting cabinet "C:\\users\\austin\\Temp\\IXP000.TMP\\msvcrt.CAB"
0069:fixme:setupapi:extract_cabinet_file awful hack: extracting cabinet "C:\\users\\austin\\Temp\\IXP000.TMP\\mtxfiles.CAB"
0069:fixme:setupapi:extract_cabinet_file awful hack: extracting cabinet "C:\\users\\austin\\Temp\\IXP000.TMP\\MDACxpak.CAB"
0069:fixme:setupapi:SetupDefaultQueueCallbackW notification 262144 params 32f2ec,0
0069:fixme:setupapi:extract_cabinet_file awful hack: extracting cabinet "C:\\users\\austin\\Temp\\IXP000.TMP\\MDACxpak.CAB"
0069:fixme:setupapi:extract_cabinet_file awful hack: extracting cabinet "C:\\users\\austin\\Temp\\IXP000.TMP\\SQLXMLXP.CAB"
0069:fixme:setupapi:extract_cabinet_file awful hack: extracting cabinet "C:\\users\\austin\\Temp\\IXP000.TMP\\sqlnet.cab"
0069:fixme:setupapi:extract_cabinet_file awful hack: extracting cabinet "C:\\users\\austin\\Temp\\IXP000.TMP\\sqlodbc.cab"
0069:fixme:setupapi:extract_cabinet_file awful hack: extracting cabinet "C:\\users\\austin\\Temp\\IXP000.TMP\\SQLOLDB.CAB"
0069:fixme:setupapi:extract_cabinet_file awful hack: extracting cabinet "C:\\users\\austin\\Temp\\IXP000.TMP\\JETFILES.CAB"
0069:fixme:setupapi:extract_cabinet_file awful hack: extracting cabinet "C:\\users\\austin\\Temp\\IXP000.TMP\\BIDINTRX.CAB"
Setting Windows version to winxp
Executing wine regedit /S C:\windows\Temp\_mdac28\set-winver.reg
------------------------------------------------------
Running /usr/local/bin/wineserver -w. This will hang until all wine processes in prefix=/home/austin/.wine terminate
------------------------------------------------------
0
```

The output implies some service (probably from whatever application(s) are installed) is crashing. Does this happen in a new prefix?

**Comment by copy** [comment] 2018-07-27 22:40
Having the same problem without the crash in the end. Same issue as #707.

```
% export WINEPREFIX=~/DL/test ; wineserver -k ; rm -rf $WINEPREFIX ; WINEARCH=win32 winetricks mdac28 ; echo $?
Using winetricks 20180603 - sha256sum: cad4e699f55c297afe5b177d68dccf1ef54e9dd23518a6f6343caa0ab7636615 with wine-3.13 and WINEARCH=win32
Executing w_do_call mdac28
Executing load_mdac28 
Using native,builtin override for following DLLs: mtxdm odbc32 odbccp32 oledb32
Executing wine regedit C:\windows\Temp\_mdac28\override-dll.reg
Setting Windows version to nt40
Executing wine regedit C:\windows\Temp\_mdac28\set-winver.reg
Executing cd /home/fabian/.cache/winetricks/mdac28
Executing wine mdac_typ.exe
005d:err:winediag:xrandr12_init_modes Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
005b:err:winediag:xrandr12_init_modes Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
0064:err:winediag:xrandr12_init_modes Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
0064:err:richedit:ReadStyleSheet skipping optional destination
0064:err:richedit:ReadStyleSheet skipping optional destination
0064:err:richedit:ReadStyleSheet skipping optional destination
0064:err:richedit:ReadStyleSheet skipping optional destination
0064:err:richedit:ReadStyleSheet skipping optional destination
0065:fixme:setupapi:SetupAddInstallSectionToDiskSpaceListA Stub
[…]
0065:fixme:setupapi:SetupAddInstallSectionToDiskSpaceListA Stub
0068:fixme:setupapi:extract_cabinet_file awful hack: extracting cabinet "C:\\users\\fabian\\Temp\\IXP000.TMP\\msvcrt.CAB"
0068:fixme:setupapi:extract_cabinet_file awful hack: extracting cabinet "C:\\users\\fabian\\Temp\\IXP000.TMP\\mtxfiles.CAB"
0068:fixme:setupapi:extract_cabinet_file awful hack: extracting cabinet "C:\\users\\fabian\\Temp\\IXP000.TMP\\MDACxpak.CAB"
0068:fixme:setupapi:SetupDefaultQueueCallbackW notification 262144 params 1123ecc,0
0068:fixme:setupapi:extract_cabinet_file awful hack: extracting cabinet "C:\\users\\fabian\\Temp\\IXP000.TMP\\MDACxpak.CAB"
006a:err:winediag:xrandr12_init_modes Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
0068:fixme:setupapi:extract_cabinet_file awful hack: extracting cabinet "C:\\users\\fabian\\Temp\\IXP000.TMP\\MDACxpak.CAB"
0068:err:setupapi:SetupDefaultQueueCallbackW copy error 32 L"C:\\users\\fabian\\Temp\\IXP000.TMP\\msdaorar.dll" -> L"C:\\Program Files\\Common Files\\System\\OLE DB\\msdaorar.dll"
006e:err:winediag:xrandr12_init_modes Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
------------------------------------------------------
Note: command wine mdac_typ.exe returned status 5. Aborting.
------------------------------------------------------
1
% wine --version
wine-3.13
% winetricks --version
20180603 - sha256sum: cad4e699f55c297afe5b177d68dccf1ef54e9dd23518a6f6343caa0ab7636615
```

Note that it behaves differently with `-q`:

```
fabian@nyu ~ % export WINEPREFIX=~/DL/test ; wineserver -k ; rm -rf $WINEPREFIX ; WINEARCH=win32 winetricks -q mdac28 ; echo $?
Using winetricks 20180603 - sha256sum: cad4e699f55c297afe5b177d68dccf1ef54e9dd23518a6f6343caa0ab7636615 with wine-3.13 and WINEARCH=win32
Executing w_do_call mdac28
Executing load_mdac28 
Using native,builtin override for following DLLs: mtxdm odbc32 odbccp32 oledb32
Executing wine regedit /S C:\windows\Temp\_mdac28\override-dll.reg
Setting Windows version to nt40
Executing wine regedit /S C:\windows\Temp\_mdac28\set-winver.reg
Executing cd /home/fabian/.cache/winetricks/mdac28
Executing wine mdac_typ.exe /q /C:setup /qnt
005d:err:winediag:xrandr12_init_modes Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
005b:err:winediag:xrandr12_init_modes Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
Setting Windows version to winxp
Executing wine regedit /S C:\windows\Temp\_mdac28\set-winver.reg
------------------------------------------------------
Running /usr/bin/wineserver -w. This will hang until all wine processes in prefix=/home/fabian/DL/test terminate
------------------------------------------------------
------------------------------------------------------
mdac28 install completed, but installed file /home/fabian/DL/test/dosdevices/c:/Program Files/Common Files/System/ADO/msado27.tlb not found
------------------------------------------------------
1
```

**Comment by Tubbles** [comment] 2018-07-28 11:45
@austin987 How can I install your version of winetricks? I.e. `winetricks 20180603-next - sha256sum: 4035b5cf1fd478d27f390b0c2d3f310d7334bd16484e6ca70396e333369a7052`

I noticed that the crash in the end only happened when I ran the original command with all the packages from OP, so it might not be related to mdac28.

Do you guys think this is an issue with winetricks, or wine, or mdac?

I am btw running on:
```
$ uname -a
Linux atop 4.17.8-1-ARCH #1 SMP PREEMPT Wed Jul 18 09:56:24 UTC 2018 x86_64 GNU/Linux
```

**Comment by austin987** [comment] 2018-08-05 05:40
@Tubbles That was HEAD at the time, so https://raw.githubusercontent.com/Winetricks/winetricks/58750aa39657757dcd6f57a4ca54806e3feb8843/src/winetricks

I'm not sure who's at fault TBH, but either wine or winetricks.

**Comment by keyunlocker12** [comment] 2018-08-05 23:12
who can help my solve this please?

plugplay:handle_bus_relations load driver L"WineHID"


I am using kali rolling

**Comment by koponomarenko** [comment] 2018-08-07 14:55
@Tubbles , is there a workaround? I'm having the same issue.

**Comment by austin987** [comment] 2018-08-12 05:04
I'd suggest filing a Wine bug and include a link to it here (feel free to CC me on it).

**Comment by austin987** [comment] 2018-08-13 20:37
I can reproduce it in staging, but not plain wine. I filed https://bugs.winehq.org/show_bug.cgi?id=45627 upstream for it.

**Comment by keyunlocker12** [comment] 2018-08-14 04:17
OK thanks

**Comment by owcmaster** [comment] 2018-09-14 22:03
I have the same issue with a fresh installed distro, standard wine @ 64 bit running at kernel 4.18.6-1

**Comment by Lemmmy** [comment] 2018-10-11 20:07
Still happening here, on wine 3.17 and wine-staging 3.17, winetricks 20180815 9343f9174146c0fa4d34e18e05269ae772a45ba78e3d8786829fa21895f6f7f4. 4.18.12-zen1-1-zen archlinux

**Comment by owcmaster** [comment] 2018-10-29 09:51
This bug is still not fixed in version 3.19.

**Comment by austin987** [comment] 2018-10-29 10:06
It would be more helpful to confirm the upstream wine bug:
https://bugs.winehq.org/show_bug.cgi?id=45627

**Comment by owcmaster** [comment] 2018-10-31 11:39
> It would be more helpful to confirm the upstream wine bug:
> https://bugs.winehq.org/show_bug.cgi?id=45627

That is already confirmed, but there doesn't seem to be any movement

**Comment by rickdj** [comment] 2018-11-13 13:13
> > It would be more helpful to confirm the upstream wine bug:
> > https://bugs.winehq.org/show_bug.cgi?id=45627
> 
> That is already confirmed, but there doesn't seem to be any movement

Hi guys, I'm also confirming that Fedora 28, wine 3.19. is getting the same issue so, that is really bad cuz I've to downgrade wine 3.19 on Fedora 28 to wine 3.5.1 in order to have the application working.

I'm hoping that this can be fixed soon.

**Comment by gverm** [comment] 2018-11-26 09:05
Could you all retest with wine-3.21? There were some fixes related to this and one person already said it was fixed for him.

**Comment by luukvbaal** [comment] 2018-11-26 09:18
Yeah it installs fine on 3.21.

**Comment by owcmaster** [comment] 2018-11-26 14:55
I will let you guys know when Manjaro/Arch releasing the new updates.

**Comment by austin987** [comment] 2018-12-04 01:40
Added a note for users using < 3.21:
https://github.com/Winetricks/winetricks/commit/44815cdb60bdde8f26149691f445db0c76e5c528

Not much more we can do, since it was upstream. Closing.

**Closed by austin987** 2018-12-04 01:40 UTC
Labels: download, upstream, wine-staging

**Comment by mikepollitt** [comment] 2023-07-21 01:52
Hi, leaving this comment in case it helps others with a similar issue. This error arose for me during installation of `jet40`. `mdac27` is a prerequisite, and during installation of that prerequisite I get the same error noted above. This was due to a hidden popup demanding that Internet Explorer be installed as a prerequisite. The popup (for me) was hidden because I was installing thus: `xvfb-run -a winetricks --unattended --force -q jet40`. I realise smarter winers may consider this a noob error, nevertheless I thought perhaps other noobs might arrive here with looking for answers. :-)
