### ISSUE TITLE
mfc42 returned error 53

### ISSUE THREAD

**Issue by ghost** [Winetricks/winetricks#1741] opened 2021-04-10 03:16 UTC
Trying to install mfc42 with winetricks results in  `wine: failed to open L`  and `returned status 53. Aborting.`. tried using both wine-6.5 and wine-6.5 (Staging) aswell as reinstalling and uninstalling winetricks (version: 20210206). also tried deleting and recreating new prefixes, mfc42 wont install. mfc70 works though and that installs fine.

32 prefix normal wine
```
Creating WINEPREFIX "/home/computer/.local/share/wineprefixes/32bit" with WINEARCH=win32
------------------------------------------------------
wine: created the configuration directory '/home/computer/.local/share/wineprefixes/32bit'
0048:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hr 0x80004002
0048:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, hr 0x80004002
0048:err:ole:apartment_get_local_server_stream Failed: 0x80004002
0050:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hr 0x80004002
0050:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, hr 0x80004002
0050:err:ole:apartment_get_local_server_stream Failed: 0x80004002
0050:err:ole:start_rpcss Failed to open RpcSs service
0064:fixme:file:NtLockFile I/O completion on lock not implemented yet
0064:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0064:err:mscoree:LoadLibraryShim error reading registry key for installroot
0064:err:mscoree:LoadLibraryShim error reading registry key for installroot
0064:err:mscoree:LoadLibraryShim error reading registry key for installroot
0064:err:mscoree:LoadLibraryShim error reading registry key for installroot
006c:fixme:file:NtLockFile I/O completion on lock not implemented yet
006c:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
006c:err:mscoree:LoadLibraryShim error reading registry key for installroot
006c:err:mscoree:LoadLibraryShim error reading registry key for installroot
006c:err:mscoree:LoadLibraryShim error reading registry key for installroot
006c:err:mscoree:LoadLibraryShim error reading registry key for installroot
006c:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 5)
006c:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 5)
0064:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 1)
0064:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 1)
wine: configuration in L"/home/computer/.local/share/wineprefixes/32bit" has been updated.
Executing w_do_call mfc42
Executing mkdir -p /home/computer/.local/share/wineprefixes
Executing load_mfc42 
Executing wine /home/computer/.cache/winetricks/vcrun6/vc6redistsetup_deu.exe /T:C:\windows\Temp\_32bit /c
wine: failed to open L"/home/computer/.cache/winetricks/vcrun6/vc6redistsetup_deu.exe": c0000135
------------------------------------------------------
warning: Note: command wine /home/computer/.cache/winetricks/vcrun6/vc6redistsetup_deu.exe /T:C:\windows\Temp\_32bit /c returned status 53. Aborting.
```

and on staging with 64 prefix

```
[computer@computer-tobefilledbyoem` ~]$ winetricks mfc42
Executing mkdir -p /home/computer
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20210206 - sha256sum: fca9fc58fa48951cecf67b8d42aa6b947f90307a08415d9403d2b8913e03a1d7 with wine-6.5 (Staging) and WINEARCH=win64
Executing w_do_call mfc42
Executing mkdir -p /home/computer
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_mfc42 
Executing wine /home/computer/.cache/winetricks/vcrun6/vc6redistsetup_deu.exe /T:C:\windows\Temp /c
wine: failed to open L"/home/computer/.cache/winetricks/vcrun6/vc6redistsetup_deu.exe": c0000135
------------------------------------------------------
warning: Note: command wine /home/computer/.cache/winetricks/vcrun6/vc6redistsetup_deu.exe /T:C:\windows\Temp /c returned status 53. Aborting.

```

anyone else having this issue? 
thanks

**Comment by 0Dragonmoon** [comment] 2021-04-10 03:48
i seem to be able to install any other .dll just fine, its that

**Comment by gverm** [comment] 2021-04-10 10:42
@0Dragonmoon I would suggest to try in a new prefix with wine-6.6. There were some loader regressions that should be fixed there. At least it works fine for me with winetricks-git and wine-6.6.

**Comment by hackerncoder** [comment] 2021-04-10 12:48
I have the same problem both with wine-6.5 and wine-6.6

**Comment by 0Dragonmoon** [comment] 2021-04-12 14:49
a workaround is to run the redist.exe as a root prefix to extract the vbrun60sp6.exe and then run that with the normal prefix.

**Comment by 0Dragonmoon** [comment] 2021-04-18 17:34
Updated to wine-6.6 staging still same issue.

**Comment by austin987** [comment] 2021-04-18 19:56
I can't reproduce this with wine-6.6.

**Comment by gverm** [comment] 2021-04-22 13:11
On ArchLinux I was actually able to reproduce this, while I wasn't able to on macOS.
I'll try to do a bisect, but it'll be difficult because of all the loader regressions.

**Comment by dron1885** [comment] 2021-04-29 14:33
I'm on Arch linux, met the same bug. Winetricks downloads the VC6RedistSetup_deu.exe but tries to run vc6redistsetup_deu.exe. Note the case mismatch. Renaming file in cache fixes install.

**Comment by 0Dragonmoon** [comment] 2021-04-30 01:10
Just tested on the latest commit https://github.com/Winetricks/winetricks/commit/aafcf5fad9345e4c416249ea3acda39b4ca33c1a by austin987 and it seems to be fixed. nice!

**Closed** 2023-02-02 09:51 UTC
Labels: help wanted
