### ISSUE TITLE
Winetricks won't start with 64-bit WINEPREFIX, Ubuntu 23.04 packaged Wine

### ISSUE THREAD

**Issue by mack-w** [Winetricks/winetricks#2084] opened 2023-06-29 16:41 UTC
On Ubuntu 23.04 with packaged Wine version Ubuntu 8.0~repack-4, Winetricks refuse to start with a 64-bit fresh WINEPREFIX.  
Console startup log:
```------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
------------------------------------------------------
WINEPREFIX INFO:
Drive C: total 28
drwxr-xr-x  7 user users 4096 Jan  1 00:00 .
drwxr-xr-x  4 user users 4096 Jan  1 00:00 ..
drwxr-xr-x  3 user users 4096 Jan  1 00:00 ProgramData
drwxr-xr-x  6 user users 4096 Jan  1 00:00 Program Files
drwxr-xr-x  6 user users 4096 Jan  1 00:00 Program Files (x86)
drwxr-xr-x  4 user users 4096 Jan  1 00:00 users
drwxr-xr-x 18 user users 4096 Jan  1 00:00 windows

Registry info:
/home/user/.wine/system.reg:#arch=win64
/home/user/.wine/user.reg:#arch=win64
/home/user/.wine/userdef.reg:#arch=win64
------------------------------------------------------
------------------------------------------------------
warning: wine cmd.exe /c echo '%AppData%' returned empty string, error message "" 
------------------------------------------------------
```    
  
  
With a 32-bit WINEPREFIX, Winetricks boot with no complaints.

Winetricks version: 20230212-next sha256sum 0f7e30aee05ab6747ef0d6a089830b91f90a4f70534b6ec581e75ef1eb71fa68

**Comment by Cieniek** [comment] 2023-06-30 11:43
That's true. Problem does not exist on official stable package from WineHQ (winehq-stable 8.0.1~lunar-1)

Package source: https://wiki.winehq.org/Ubuntu

**Comment by austin987** [comment] 2023-07-05 03:36
Sounds like a packaging bug to me, have you reported this to Ubunut?

**Comment by gel-crabs** [comment] 2023-07-10 05:46
This happens on Arch Linux as well with a wow64-only build of Wine

**Comment by Kzimir** [comment] 2023-07-15 21:57
Does not work with Wine built manually with old and new wow64 build.
The warning seems incorrect because AppData exists and not empty.

**Comment by austin987** [comment] 2023-07-16 06:47
> This happens on Arch Linux as well with a wow64-only build of Wine

I'm not sure what 'wow64-only' means. If you mean a build with `--enable-win64` but without the corresponding 32-bit build, that's not supported upstream (and so also not supported by winetricks).

> Does not work with Wine built manually with old and new wow64 build. 

If this is a regression for your setup, it would be helpful if you could bisect it. It sounds like a change upstream, I can't reproduce locally.

> The warning seems incorrect because AppData exists and not empty.

Yes; I suspect the real issue is a race condition and this just happens to be where the failure is encountered.

**Comment by Kzimir** [comment] 2023-07-16 07:10
> If this is a regression for your setup, it would be helpful if you could bisect it. It sounds like a change upstream, I can't reproduce locally.

My setup is a fresh install of Debian Sid. I tried with old winetricks version "20220411" and "20210825" and i have the same error message.

Possible to be an issue with Wine directly ?

**Comment by austin987** [comment] 2023-07-16 07:17
> Possible to be an issue with Wine directly ?

That's my suspicion, yes.

**Comment by ziqingh** [comment] 2023-07-18 03:14
If we build wine with the new WoW approach:
`cd wine && ./configure --enable-archs=i386,x86_64 && make`

The wineprefix will be a 64-bit prefix, however, there is only a `wine` executable, no `wine64`.

winetricks recogonize the prefix as 64-bit, and use `wine64` as wine executable, which leads to the issue that in `winetricks_set_wineprefix()`, we are using a non-existent wine64 as wine executable.

**Comment by austin987** [comment] 2023-07-18 04:17
> If we build wine with the new WoW approach: `cd wine && ./configure --enable-archs=i386,x86_64 && make`

That's covered by #2030 (which has a patch, and feedback would be appreciated).

This issue is about Ubuntu packaged wine (which I don't believe uses the new wow64 approach, but I could be wrong).

The issue is more likely to be an issue either in upstream Wine or in Ubuntu's packaging. If someone wants to help track it down, trying to downgrade wine/winetricks would help narrow down which introduced the bug.

If the bug is a Ubuntu packaging bug, a launchpad issue should be opened.

If it's a Wine bug, a regression test should be performed and a bug opened on bugs.winehq.org.

If it's a Winetricks bug, a regression test would also be helpful.

**Comment by austin987** [comment] 2023-07-23 17:07
Sounds like this may be related to https://bugs.winehq.org/show_bug.cgi?id=55139

**Comment by KenSharp** [comment] 2023-07-25 22:44
It is indeed the same issue.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1031649

**Comment by Kzimir** [comment] 2023-08-22 17:23
Austin, i tried winetricks + https://github.com/austin987/winetricks/commit/73dc70c9d03a4171048c280bf956a981d6de4f21 and it does not work for me ... :/

**Comment by RinH22** [comment] 2023-10-30 03:23
On Ubuntu 23.04, I switched my wine install to the stable branch earlier this year to avoid a regression that was in the development branch. This same bug is happening to me. I'm still on the (Ubuntu 8.0~repack-4) stable install. Perhaps one of wine's recent bug fixes caused a regression that was included in the the 3/4 repack?

**Comment by austin987** [comment] 2024-01-04 06:28
Duplicate of #2119 (I realize this one is older, but that one has a linked PR).

**Closed by austin987** 2024-01-04 06:28 UTC

**Comment by melroy89** [comment] 2024-02-17 23:59
@austin987 Please review this issue, various users of WineGUI are suffering from this issue with Winetricks. 
This `wine cmd.exe /c echo '%AppData%' returned empty string ,error message ""` error is present in various distros like Ubuntu, Zorin OS, SparkyLinux and Debian.

The problem is **NOT** solved with the latest Winetricks version (20240105-next). The issue you refer to is also closed (https://github.com/Winetricks/winetricks/issues/2119). Again, the problem isn't resolved however.

**Comment by ehabibov** [comment] 2024-07-27 11:38
Using Whisky 2.3.2 (40) and MBP M1 with Sonoma 14.1.2 on board I also facing winetricks issue:
```
------------------------------------------------------
------------------------------------------------------
warning: wine64 cmd.exe /c echo '%AppData%' returned empty string, error message "" 
------------------------------------------------------
```

**Comment by austin987** [comment] 2024-08-02 02:15
Try with latest (master), a fix went in a while back.

**Comment by RinH22** [comment] 2024-08-15 11:00
Just adding my two cents since I forgot I was subscribed to this thread. As stated above I had issues on Ubuntu 23.10. When the upgrade to Ubuntu 24.04 happened, this issue was resolved for me. I'm now also using LMDE6 with no issues. And I can use stable or development as I like.

**Comment by ErikSchulp** [comment] 2024-08-30 07:05
And another 2 cents, I am on Zorin OS 17.1 jammy and had this error too, sudo winetricks --self-update fixed it for me.

**Comment by MeneerJansen** [comment] 2025-07-03 10:54
> And another 2 cents, I am on Zorin OS 17.1 jammy and had this error too, sudo winetricks --self-update fixed it for me.

*That* was the hat trick. Didn't know that command existed. Thanks man!

**Comment by yekkusu** [comment] 2025-10-07 23:47
> And another 2 cents, I am on Zorin OS 17.1 jammy and had this error too, sudo winetricks --self-update fixed it for me.

Thank you, this did the trick for me too, without it I wouldn't be able to run the winetricks dotnet462 command, and I need that old thing to activate my Scrivener copy :) Now I can work in peace.

**Comment by W1M0R** [comment] 2026-04-29 14:46
This resolved the issue for me on NixOS: https://github.com/NixOS/nixpkgs/issues/338367#issuecomment-3759333790
