### ISSUE TITLE
Binkw32 checksum mismatch.

### ISSUE THREAD

**Issue by JavelinHeadQueer** [Winetricks/winetricks#1656] opened 2020-12-04 22:03 UTC
Don't know why this is happening. Updated winetricks from source. Need this to run a game.
I'm on Ubuntu 20.04, I'm not technically savvy enough to provide logs without direction.
I'm trying to install binkw32 via winetricks in Lutris.

**Comment by austin987** [comment] 2020-12-05 16:16
It's already fixed by https://github.com/Winetricks/winetricks/commit/b7c2f239f88687396554d57e454e8d3b897904e1

**Closed by austin987** 2020-12-05 16:16 UTC

**Comment by Chiitoo** [comment] 2020-12-06 02:02
> I don't understand anything of what you posted.

It means the issue is fixed, but the version of the Winetricks script that you are using is old enough to not have the change yet.  It looks like this commit happened after the latest release, so you'd probably want to try downloading the "git master" version and use that instead (or make Lutris use it, if possible).
