### ISSUE TITLE
I can't install FlashDevelop...plz help me...

### ISSUE THREAD

**Issue by minphone** [Winetricks/winetricks#696] opened 2016-11-12 21:24 UTC
[FlashDevelop_install.log.zip](https://github.com/Winetricks/winetricks/files/587455/FlashDevelop_install.log.zip)

**Comment by austin987** [comment] 2016-11-13 02:04
On Nov 12, 2016 3:24 PM, "minphone" <notifications@github.com> wrote:
>
> FlashDevelop_install.log.zip
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

How is this a winetricks bug?

**Comment by qwertychouskie** [comment] 2016-11-13 02:11
Because it fails when running Winetricks.  Seems to be a dupe of https://github.com/Winetricks/winetricks/issues/695.  Also @minphone you are using an old Wine version, you should upgrade to 1.8.5 or 1.9.23.

**Comment by austin987** [comment] 2016-11-13 02:14
Thanks, I see it now, yes, a dupe.

I was confused because winetricks doesn't have this app, must be a custom
verb in winebottler.

**Comment by minphone** [comment] 2016-11-13 08:34
plz share latest version link...

**Comment by austin987** [comment] 2016-11-15 07:58
I pushes some fixes that you can test here:
https://raw.githubusercontent.com/Winetricks/winetricks/w_download_fixes/src/winetricks

I'll be merging that to master once the tests complete / pass.

Anyway, I'm going to close this since it's a duplicate of #695, which will be updated when master is fixed.

**Closed by austin987** 2016-11-15 07:58 UTC
