### ISSUE TITLE
winetricks is broken under box86 (wine --version has extraneous output)

### ISSUE THREAD

**Issue by LucAstrand** [Winetricks/winetricks#1600] opened 2020-08-29 14:40 UTC
Hi, 
i am currently trying to install,  Magic the gathering Online. I have installed both wine and winetricks, trying to get it working, however, whenever i try to install the needed .Net framework, i get greeted by different errors, like:
Downloading https://web.archive.org/web/http://download.microsoft.com/download/3/F/0/3F0A922C-F239-4B9B-9CB0-DF53621C57D9/dotnetfx3.exe failed.
I then tried installing .Net manually, leading to another error stopping the installation. 
this time it was a sha1sum mismatch error.
My wine version is: wine-5.13
and my winetricks version is: 20170101 - sha1sum: c844fda0cca25ac9ed0ed1b55cd138cab6a4af16
I would also like to point out i am on a Raspberry pi 4, using Box86 in conjunction with wine.
Thanks in advance!

**Comment by SwimmingTiger** [comment] 2020-08-31 11:23
This PR can fix it:
https://github.com/Winetricks/winetricks/pull/1599

**Comment by austin987** [comment] 2020-09-02 00:05
I'm still splitting/testing, but if you're able, please test with:
https://raw.githubusercontent.com/austin987/winetricks/wip/src/winetricks

branch is at:
https://github.com/austin987/winetricks/tree/wip

There's still work to be done on the w_package_broken* bits before I push any of it, but it's close to ready, so I'd like others to test before I push anything.

**Comment by LucAstrand** [comment] 2020-09-02 19:17
Thanks, for the response!
i have tried testing suggested "https://raw.githubusercontent.com/austin987/winetricks/wip/src/winetricks", however i am encountering another problem. 
Whenever i run any winetricks command, it says that wine 5.13 is not supported upstream, and that i should update do 4.xx, rendering it impossible to go any further.

**Comment by austin987** [comment] 2020-09-03 03:31
Could you attach the output of `winetricks -q -v good` &> output.txt?

**Comment by LucAstrand** [comment] 2020-09-03 19:05
Ok, i have no clue what changed, since i have not used my pc since the last response, but i no longer get the wine 5.13 is not supported upstream, and that i should update do 4.xx error, i only get this one:
bug: w_metadata adobeair corrupt, might need forward slashes?
Attached you will find the output.txt i obtained running "winetricks -q -v good &> output.txt" using wine 5.13 and the version of winetricks you suggested in your previous message.
[output.txt](https://github.com/Winetricks/winetricks/files/5170669/output.txt)

I also never installed wine mono or wine gecko.

Thank you for everything!

**Comment by austin987** [comment] 2020-09-04 09:33
@LucAstrand the problem is in your wine wrapper:
```
+ echo Using winetricks 20200412-next - sha256sum: d7e6bb5935ca76f9a22a3658bd8610e74c2a7222f5930d6fd57cdce812ca91a8 with Dynarec for ARM, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096
BOX86: Wine detected, WINEPRELOADRESERVE=""
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/
Using default BOX86_PATH: ./:bin/
Counted 50 Env var
wine
argv[1]="--version"
wine.so.1
...
```

that's the output from `wine --version`, when normally it would be something like `wine-5.14`. The extra output is breaking winetricks' parsing.

**Comment by LucAstrand** [comment] 2020-09-04 19:44
I see, the extra lines you see are from Box 86 which is needed in order to run wine/other x86 programs on ARM devices (i am using it since i am on a raspberry pi 4), i will link BOX 86's github for reference. "https://github.com/ptitSeb/box86"
It is still in its very early stages, so it isn't perfect. I guess there is only so much an arm machine can do right now!
Thank you for all the support you have given me, and for the amazing program you are working on!

**Comment by austin987** [comment] 2020-09-05 07:48
Taking a look upstream, sounds like box86 may have (or be working on), supporting/integrating wine in some way (which makes sense, given `BOX86: Wine detected, WINEPRELOADRESERVE=""`).

I'd suggest making sure that, e.g., you can get `wine notepad` to work before trying anything with winetricks. I suspect you may need patches to winetricks and/or box86 to get things to work. For starters, I'd try patching box86 to print that output to a logfile, stderr, or make it off by default and enabled with a verbose option. In theory, that would get winetricks further (and likely to another problem.

**Comment by LucAstrand** [comment] 2020-09-05 09:31
I can confirm that wine notepad runs without encountering any problems, alongside internet explorer for instance.
I would say that I am actually very impressed with how much Box86 has actually achieved. You can take a look at the Pi Labs youtube channel for many examples.
I will link this page to the Box 86 founder, to see if he could implement some of what you suggested. Thanks!

**Comment by WheezyE** [comment] 2020-09-25 18:45
I haven't made any progress on updating the older version of winetricks in TwisterOS (the OS which houses box86), but I did want to add some info to shed a little more light on what makes an old version of winetricks work with box86:

I've discovered that TwisterOS 1.8.2's winetricks (the one that box86 runs by default, current as of 9/25/2020) is a patched version of the [original 20170101 winetricks](https://github.com/Winetricks/winetricks/releases/tag/20170101) release.  I've made a [diff patch here](https://pastebin.com/tL9Gx5wK) for anyone who wants to patch original winetricks 20170101 to create the TwisterOS version of winetricks.  Without the patches, winetricks won't run with box86+[i386 wine](https://twisteros.com/wine.tgz) on RPi's ARM architechture (ptitSeb said that this wine.tgz file was vanilla and unmodified, but supplied it on his website for ease of access).

Box86 can be built and installed on a vanilla Raspbian (Raspberry Pi OS) with these commands (if you don't want to install Twister OS):
```
sudo apt-get install cmake -y

cd ~/Downloads
git clone https://github.com/ptitSeb/box86.git
cd box86
mkdir build
cd build
cmake .. -DRPI4=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo
make -j4
sudo make install

cd ~/Downloads
wget https://twisteros.com/wine.tgz
tar -xvzf wine.tgz
### Then copy all the contents of the directories in the unzipped 'wine' folder to their corresponding directories in '/usr/local/'

box86 wine wineboot #start i386-wine
```

------------------------------------------------------
If you don't want to apply the diff patch (above) to see the differences between the TwisterOS winetricks and the original winetricks file, here's what is changed between those files.

WinMerge finds that these lines are changed or added in the TwisterOS version of winetricks_20170101:
(note: I think my line numbers may be relative to WinMerge)

Added after line 19420:
```
    if [ ! "$1" ] && [ "$WINETRICKS_GUI" = "none" ] ; then
       echo "Nothing to do. See --help. Graphical UI can be started with --gui"
       exit 0
    elif [ ! "$1" ] && [ "$WINETRICKS_GUI" != "none" ] ; then
       # no arguments, but gui asked.
       set -- gui
    fi
```

Changed in Line 19434:
`"")` becomes `gui)`



WinMerge finds that these lines are deleted in the TwisterOS version of winetricks_20170101:

Line 687:
```
# Checks if the user can run the self-update/rollback commands
winetricks_check_update_availability()
{
    # Prevents the development file overwrite:
    if test -d "../.git"
    then
        w_warn "You're running in a dev environment. Please make a copy of the file before running this command."
        exit;
    fi

    # Checks read/write permissions on update directories
    if ! (test -r "$0" && test -w "$0" && test -w "${0%/*}" && test -x "${0%/*}")
    then
        w_warn "You don't have the proper permissions to run this command. Try again with sudo or as root."
        exit;
    fi
}

winetricks_selfupdate()
{
    winetricks_check_update_availability

    _W_filename="${0##*/}"
    _W_rollback_file="${0}.bak"
    _W_update_file="${0}.update"

    _W_tmpdir=${TMPDIR:-/tmp}
    _W_tmpdir="$(mktemp -d "$_W_tmpdir/$_W_filename.XXXXXXXX")"

    w_download_to "$_W_tmpdir" https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks

    # 2016/10/26: now file is uncompressed? Handle both cases:
    update_file_type="$(file "$_W_tmpdir/$_W_filename")"
    case "$update_file_type" in
        *"POSIX shell script"*)
            #echo "already decompressed!"
            w_try mv "$_W_tmpdir/$_W_filename" "${_W_update_file}"
            ;;
        *"gzip compressed data"*)
            w_try mv "$_W_tmpdir/$_W_filename" "${_W_update_file}.gz"
            w_try gunzip "${_W_update_file}.gz"
            ;;
         *)
            echo "Unknown file type: $update_file_type"
            exit 1
            ;;
    esac

    w_try rmdir "$_W_tmpdir"

    w_try cp "$0" "$_W_rollback_file"
    w_try chmod -x "$_W_rollback_file"

    w_try mv "$_W_update_file" "$0"
    w_try chmod +x "$0"

    w_warn "Update finished! The current version is $($0 -V). Use 'winetricks --update-rollback' to return to the previous version."

    exit
}

winetricks_selfupdate_rollback()
{
    winetricks_check_update_availability

    _W_rollback_file="${0}.bak"

    if test -f "$_W_rollback_file"
    then
        w_try mv "$_W_rollback_file" "$0"
        w_try chmod +x "$0"
        w_warn "Rollback finished! The current version is $($0 -V)."
    else
        w_warn "Nothing to rollback."
    fi
    exit;
}
```

Line 2707
```
winetricks_latest_version_check()
{
    if [ "$WINETRICKS_LATEST_VERSION_CHECK" = 'disabled' ] || [ -f "${WINETRICKS_CONFIG}/disable-latest-version-check" ] ; then
        w_info "winetricks latest version check update disabled"
        return
    fi

    latest_version="$(winetricks_dl_url_to_stdout https://raw.githubusercontent.com/Winetricks/winetricks/master/files/LATEST)"

    # Also check that $latest_version is an actual number in case github is down
    if [ ! -z "${latest_version}" ] && [ ! "$WINETRICKS_VERSION" = "${latest_version}" ] && \
        echo "${latest_version}" | grep -E "[0-9]{8}" ; then

        if [ -f "${WINETRICKS_CONFIG}/enable-auto-update" ] ; then
            w_info "You are running winetricks-${WINETRICKS_VERSION}."
            w_info "New upstream release winetricks-${latest_version} is available."
            w_info "auto-update enabled: running winetricks_selfupdate"
            winetricks_selfupdate
        else
            w_warn "You are running winetricks-${WINETRICKS_VERSION}, latest upstream is winetricks-${latest_version}!"
            w_warn "You should update using your distribution's package manager, --self-update, or manually."
        fi
    fi
}
```

Line 4622:
```
    winetricks_latest_version_check
```

Line 4695:
```
    --self-update     Update this application to the last version
    --update-rollback Rollback the last self update
```

Line 4738:
```
    --self-update) winetricks_selfupdate;;
```

Line 4741:
```
    --update-rollback) winetricks_selfupdate_rollback;;
```

**Comment by WheezyE** [comment] 2020-09-26 21:47
Oh I misunderstood the problem.  I was having a different problem which ended up being mostly due to my not restarting the Pi after installing box86 and wine (or maybe just not refreshing the shell window?) and Box86 just didn't know to initialize my i386 wine files on the ARM Pi by running wine through box86.

So, the above diff patch and analysis is interesting, but not really needed: The 20170101 winetricks that comes with TwisterOS is different, but the official 20170101 winetricks works fine too.

To OP's point: I also encountered the SHA mismatch error, but I believe that this is a problem with using an older winetricks version.


I did make some interesting progress though to get the latest winetricks working with my box86 install.
------------------------------------------------------

I also encountered newer versions of winetricks (like 20200412) complaining about the version of wine that we're running (`Using
5.13 is no longer supported upstream. You should upgrade to 4.x`), but winetricks didn't quit after complaining about it.

However, when I tried to run any winetricks newer than 20170326 (20170326 works, but 20170327 doesn't), my main problem was actually winetricks freezing on this error message:
```
------------------------------------------------------
bug: w_metadata adobeair corrupt, might need forward slashes?
------------------------------------------------------
```
It turns out that changing/patching `echo "${arg%%=*}"=\""${arg#*=}"\"` to `echo ${arg%%=*}=\"${arg#*=}\"` (line 2853 in winetricks-20200412) gets around the above `bug: w_metadata adobeair corrupt` error.

Some older (20170326) winetricks' had old links and would error on not being able to download files, but the current (20200412) winetricks (with the above _adobeair corrupt_ patch), works for me just fine.

There are still some problems with box86 where, say, dotnet35sp1 will error though with `wine client error:24:  read: Bad address` when dotnet is "Extracting Files"

**Comment by WheezyE** [comment] 2020-11-26 02:08
Just wanted to update this thread.  This has been fixed in box86 now and I think we can close this thread.

If you want to run winetricks with box86, you should preface your winetricks command with `BOX86_NOBANNER=1`. You can also use the patch above, but this is a more elegant solution.

For example: `BOX86_NOBANNER=1 winetricks dotnet20`

_Also note: If you're running TwisterOS, make sure to update your winetricks, as Twister OS uses an old version of winetricks that has outdated links to downloading files._

**Closed** 2021-02-08 19:38 UTC
