### ISSUE TITLE
bug: w_metadata adobeair corrupt, might need forward slashes?

### ISSUE THREAD

**Issue by blackdedz** [Winetricks/winetricks#981] opened 2018-05-05 18:12 UTC
When i try install winetricks that happend:

------------------------------------------------------
Your version of wine 3.0
Parent

Parent is no longer supported upstream. You should upgrade to 2.x
------------------------------------------------------
Using winetricks 20180217-next - sha256sum: 58c2b68fcb238b2de6fe5f75abaf88945776cf8f1fcadaca7f115b825dece7c6 with wine-3.0 (Debian 3.0-1)
Parent pid 6148, child pid 6153

Parent is shutting down, bye... and WINEARCH=win32
installed_file1="C:\Program Files\Common Files
Parent pid 5848, child pid 5853
------------------------------------------------------
bug: w_metadata adobeair corrupt, might need forward slashes?

Help me please!!

**Comment by austin987** [comment] 2018-05-08 08:47
Dupe of #909, GUI only bug;use the CLI as a workaround.

**Closed by austin987** 2018-05-08 08:47 UTC

**Comment by Bebef** [comment] 2018-05-14 18:16
Unfortunately I have the same issue using CLI only:

```$./winetricks prefix=~/.winedotnet40/ list-installed
------------------------------------------------------
Your version of wine 3.0
Parent

Parent is no longer supported upstream. You should upgrade to 2.x
------------------------------------------------------
Using winetricks 20180513 - sha256sum: 09f793f2b57f03e95dc14f590d475a78769e227f8d3e3c54c135ee6c44aacd30 with wine-3.0 (Debian 3.0-1)
Parent pid 11008, child pid 11013

Parent is shutting down, bye... and WINEARCH=win32
installed_file1="C:\Program Files\Common Files
Parent pid 10709, child pid 10714
------------------------------------------------------
bug: w_metadata adobeair corrupt, might need forward slashes?
------------------------------------------------------
```

I also tried the latest file from Master, that didn't help either. Anything else I could try? :confused:

**Comment by Bebef** [comment] 2018-05-14 18:28
@austin987 That's it exactly, was able to work aroud using `firejail --noprofile winetricks`

Thanks! :+1: :smiley:
