### ISSUE TITLE
REQUEST: refactor of w_workaround_bug using info from bugzilla

### ISSUE THREAD

**Issue by Kreyren** [Winetricks/winetricks#1392] opened 2019-10-21 14:16 UTC
We can use `curl https://bugs.winehq.org/show_bug.cgi?id=47565 2>/dev/null | grep "static_bug_status"` to get status of winebug directly from bugzilla: 

```console
kreyren@dreamon:~$ curl https://bugs.winehq.org/show_bug.cgi?id=47565 2>/dev/null | grep "static_bug_status"
      <span id="static_bug_status">UNCONFIRMED
```

I believe that this opens new posibilities in making winetricks self-sufficient in terms of applying workarounds depending on bug status and wine used assuming that reporters fills metadata of the bug correctly alike:

```console
kreyren@dreamon:~$ curl https://bugs.winehq.org/show_bug.cgi?id=47565 2>/dev/null | grep "page.cgi?id=fields.html#version" -A 5
      href="page.cgi?id=fields.html#version"
  >Version:</a>
</label>
</th>
        <td>4.12.1
  </td>

```

To get the affected wine version, etc..

---

To make winetricks work offline we could probably stash these definitions in cache.

**Comment by austin987** [comment] 2019-10-21 23:41
It's a neat idea, but it would be tricky in practice:
A) the reported version doesn't mean much. That's only when it was _reported_, it could've been there before. In addition, users often like to change it, and triagers don't always catch it and set it back.
B) There's no field describing the fixed version. You could theoretically parse AJ's closing comment, but that's not automated and could change (and also doesn't guarantee that's when the bug _was fixed_, just _when it was reported and marked fixed_.
C) You'd want to make this optional, users with slow/no connection don't want to waste bandwidth/time, and it has privacy issues as well.

**Comment by Kreyren** [comment] 2019-10-22 00:39
> A) the reported version doesn't mean much. 

We could change Bugzilla's Metadata to allow inputting range of affected versions in that case assuming it being Bugzilla it should be easy to implement. (basically changing the default form?) 

> That's only when it was reported, it could've been there before. In addition, users often like to change it, and triagers don't always catch it and set it back.

Well if users change it on the bug we will be the first to notice it and fix it.. in then I believe it's just a matter of educating the community to know how to file the Metadata (and winedevs since lots of bugs has wrong metadata) 

> B) There's no field describing the fixed version. You could theoretically parse AJ's closing comment, but that's not automated and could change (and also doesn't guarantee that's when the bug was fixed, just when it was reported and marked fixed.

yes change in Bugzilla's Metadata would be required to allow specifying the exact affected versions from there we could make logic in winetricks. 

> C) You'd want to make this optional, users with slow/no connection don't want to waste bandwidth/time, and it has privacy issues as well.

Any idea how could we implement this?  I guess providing default definitions for bugs with winetricks releases and from there allow using function in winetricks to update them from bugzilla? 

Other then that it's probably packaging issue for downstream

for privacy winetricks has torify etc.. so in terms of privacy that should be an issue. 

---

For bugzilla i remember working on a project that had bugzilla setup in a way that only outputed formated metadata for specialized url extension. I think that it's already a part of bugzilla which would allow us to implement the function easier, but investigation is needed.

**Comment by austin987** [comment] 2019-10-23 07:26
While I could change bugzilla, I'm not going to do it willy nilly. In particular, this would require editing all fixed bugs to be useful, which is extremely impractical.

In addition if you think educating the community to follow standards is trivial, you aren't following closely. I've worked on wine bugzilla for over a decade.. It's not.

While I'm tempted to close this, I do think it's a neat idea. But requiring chess upstream impractical and will need a much, MUCH stronger argument.

That said, this isn't your blog, please keep comments to a minimum.

**Comment by Kreyren** [comment] 2019-10-23 12:03
>  this would require editing all fixed bugs to be useful, which is extremely impractical.

I believe that it would require only editing new bugs and those that are affecting winetricks to be used for logic and we can just check all bugs that are currently workarounded and edit it's metadata which i'm willing do to. 

> In addition if you think educating the community to follow standards is trivial, you aren't following closely. I've worked on wine bugzilla for over a decade.. It's not.

From my point of view current instuctions on bugzilla aren't exactly strait forward for non-winehq members.

If it was me i would just make the Version mandatory to be filled prior to submiting a bug so that bugzilla woudn't allow making a bugs that doesn't have wine version specified. Same could probably be applied for other metadata. 

> will need a much, MUCH stronger argument.

Is proposed in this comment sufficient? if not provide reasoning and i believe that we can find a sufficient solution.

---

> That said, this isn't your blog, please keep comments to a minimum.

Elaborate?

**Comment by Kreyren** [comment] 2019-11-25 05:44
headsup: Winebug submitted https://bugs.winehq.org/show_bug.cgi?id=48169

**Comment by tannisroot** [comment] 2019-12-07 07:11
> Elaborate?
i'm not Austin but you spam in this repo with various notes like it's your blog :/

**Comment by Kreyren** [comment] 2019-12-07 07:43
> i'm not Austin but you spam in this repo with various notes like it's your blog :/

Noted, aldo i don't know what else is expected from me to provide the expected contribution.

**Comment by tannisroot** [comment] 2019-12-07 07:44
If you want to contribute, making new verbs would be nice :+1:

**Comment by mirh** [comment] 2020-12-04 02:09
This doesn't really make sense. Like half of the bugs are closed and reported "fixed" tons of versions (if not years) after the *actual* fix. 
If you can get Julliard to change his reporting model after 20 years, good enough, otherwise even bugzilla parsing data by itself is useless.

**Comment by paulwratt** [comment] 2021-05-16 11:42
> Fixed by SHA1: | 7ca1c4900e42d608150822ef87a7ce2847a59b6f

maybe due to the submitted Winebug but at least that commit tag allows verification, not sure how to tie that to release version tho, without further research.

My opinion on expressive development posts: those that complain about them are usually terrible at providing documentation (in some form or another). I might remind people that a (GitHub Issues != git commit).

**Comment by paulwratt** [comment] 2021-05-16 12:27
the workaround in the "headsup" (linked) post that provides XML output is untenable for the OP url (its been (was 5 now) 10 minutes and its still not done - I just stopped it after 15min and its still going) https://bugs.winehq.org/show_bug.cgi?ctype=xml&id=47565

A compromise for Bugzilla would to be able to retrieve a header only without any comments. ie without the `<long_desc ..` tag content. https://bugs.winehq.org/show_bug.cgi?ctype=xml&id=48169

a "short=true" would allow both HTML & XML "header view"

To be concerned with the users privacy, "winetricks --self-update" would have to be dropped as that connection is now "owned by Microsoft" who are well publisied for their security and not at all know for collecting excessive amounts of telemetary.

I would suggest any winetricks url grabs be assisted by a "winetricks" browser string, at least those on bugs.winehq.com would be able to get useful information from it. I dont believe GitHub has Browser connection statistics per project, but I may be wrong, and if they do publish public stats "winetricks" would be present for "updates"

both of these seem useful to wine project, and could be extended to the other helper projects (winetricks, kreytricks, phoenicis, lutris, etc..)

a "header only" would be useful for adding data analysis to wine project management, considering the amount of regessions between versions - ie all open bugs that have winetricks workarounds - all close but not fixed (eg #1476)

actually if that 1st example was run before a winetricks version release you could verify the need for workarounds on the spot, and make adjustments to that release.

**Comment by paulwratt** [comment] 2021-05-16 13:46
you can get a "fake" header at a console shell prompt with the following:
```
N=$(curl -s "https://bugs.winehq.org/show_bug.cgi?ctype=xml&id=48169" 2>/dev/null | grep -nm 1 long_desc | cut -d \: -f 1); curl -s "https://bugs.winehq.org/show_bug.cgi?ctype=xml&id=48169" 2>/dev/null | head -n $(($N-1)) | sed '/^[[:space:]]*$/d'
```

**Comment by paulwratt** [comment] 2021-05-16 14:11
Ok so where there is a "Fixed" commit entry, the URL field is also present to the git commit, and the _taht_ page contains a _date_ that might be used to cross reference a wine version

(referenced: https://bugs.winehq.org/show_bug.cgi?id=47565)

**Comment by paulwratt** [comment] 2021-05-17 01:41
if the WineHQ Bugzilla is kept up to date with the main Bugzilla project, it would make sense to get it added there.

I also believe JSON output would be more useful (via 'jq')

there is a way to get the version based on both "Regression SHA1:" and "Fixed SHA1:" (in XML the url is passed through `bug_file_loc`), by pulling `VERSION` from a "Fixed SHA1:" (modified) url that points to the _tree_ of said commit:
https://source.winehq.org/git/wine.git/tree/7ca1c4900e42d608150822ef87a7ce2847a59b6f
https://source.winehq.org/git/wine.git/blob/7ca1c4900e42d608150822ef87a7ce2847a59b6f:/VERSION
https://source.winehq.org/git/wine.git/blob_plain/7ca1c4900e42d608150822ef87a7ce2847a59b6f:/VERSION

**Closed** 2022-04-11 10:24 UTC
Labels: enhancement
