### ISSUE TITLE
Corefonts: Copy breaks with folder containing spaces

### ISSUE THREAD

**Issue by duhow** [Winetricks/winetricks#1066] opened 2018-08-07 21:04 UTC
As reported at https://github.com/lutris/lutris/issues/1006 , doing `winetricks corefonts` with `WINEPREFIX=/home/user/folder with spaces` breaks the `cp` command. 

I tried to fix it specifying `IFS=$'\n'` but it still breaks (?)

https://github.com/Winetricks/winetricks/blob/4795145112fa73b537fccfd1dd7d347320964fb2/src/winetricks#L465-L467

**Comment by austin987** [comment] 2018-08-07 21:16
It's a bit complicated. I think I know how I want to fix, will revisit this week.

Dupe of #995

**Closed by austin987** 2018-08-07 21:16 UTC
