### ISSUE TITLE
Is the `--version` command line option misreporting the version?

### ISSUE THREAD

**Issue by outsidefactor** [Winetricks/winetricks#1904] opened 2022-04-12 09:46 UTC
Thank you for taking the time to read this post.

This issue first came to light for me when I noticed that Lutris and Protontricks were complaining that my winetricks version was old. Manjaro told me that 20210825-1 was installed, but running winetricks with the `--version` modifier reported:

`20210206-next - sha256sum: 0769bbcdbd92c407f4eacaa85acc1339f607dbeafe2febd1be0912034c7af3a1`

OK... so maybe there's a problem with that particular version. So I go and pull the `20220328-1` package from Manjaro's experimental packages repos, install it and... all the same errors are happening!

Is this a bug with winetricks misreporting its version, or is the same old build getting published to Arch and then on to Manjaro by mistake?

If I can't trust `--version` how can I verify the actual version installed?

Here's my system details if that's relevant:

System:
  Host: telperion Kernel: 5.16.14-1-MANJARO arch: x86_64 bits: 64
    Desktop: KDE Plasma v: 5.24.3 Distro: Manjaro Linux
Machine:
  Type: Desktop System: Gigabyte product: X570 AORUS ULTRA v: -CF
    serial: <superuser required>
  Mobo: Gigabyte model: X570 AORUS ULTRA serial: <superuser required>
    UEFI: American Megatrends LLC. v: F35d date: 10/13/2021
CPU:
  Info: 8-core AMD Ryzen 7 3700X [MT MCP] speed (MHz): avg: 2238
    min/max: 2200/4426
Graphics:
  Device-1: AMD Navi 22 [Radeon RX 6700/6700 XT / 6800M] driver: amdgpu
    v: kernel
  Display: wayland server: X.org v: 1.21.1.3 with: Xwayland v: 22.1.0
    compositor: kwin_wayland driver: X: loaded: amdgpu
    unloaded: modesetting,radeon gpu: amdgpu resolution: 1: 3440x1440
    2: 1920x1080
  OpenGL: renderer: AMD Radeon RX 6700 XT (NAVY_FLOUNDER DRM 3.44.0
    5.16.14-1-MANJARO LLVM 13.0.1)
    v: 4.6 Mesa 21.3.7
Network:
  Device-1: Intel Wi-Fi 6 AX200 driver: iwlwifi
  Device-2: Intel I211 Gigabit Network driver: igb
Drives:
  Local Storage: total: 10.7 TiB used: 8.96 TiB (83.7%)
Info:
  Processes: 447 Uptime: 42m Memory: 62.79 GiB used: 8.95 GiB (14.3%)
  Shell: Zsh inxi: 3.3.15

**Comment by austin987** [comment] 2022-04-12 22:14
Duplicate of #1826.

I made a new release yesterday that will resolve this (and other) issues: https://github.com/Winetricks/winetricks/releases/tag/20220411

**Closed by austin987** 2022-04-12 22:14 UTC
